{
 "title": "Product Catalog Server",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "product-catalog-dev,product-catalog-test,product-catalog-prod"
   }
  ]
 },
 "panels": [
  { "title": "API Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Method Hits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate({__name__=~\".*_count.*\",method=~\".+\",type=\"counter\", namespace=\"$namespace\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Performance 95% quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate({__name__=~\".*_seconds.*\",method=~\".+\",type=\"perf\", namespace=\"$namespace\", quantile=\"0.95\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Performance 75% quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate({__name__=~\".*_seconds.*\",method=~\".+\",type=\"perf\", namespace=\"$namespace\", quantile=\"0.75\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  { "title": "Database Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Connection Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vendor_agroal_active_count{namespace=\"$namespace\"}[5m])",
     "legendFormat": "Active ({{pod}})"
    },
    {
     "expr": "rate(vendor_agroal_available_count{namespace=\"$namespace\"}[5m])",
     "legendFormat": "Idle({{pod}})"
    }
   ]
  },
  {
   "title": "Connection Wait Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vendor_agroal_creation_time_average_seconds{namespace=\"$namespace\"}[5m])",
     "legendFormat": "Average ({{pod}})"
    },
    {
     "expr": "rate(vendor_agroal_blocking_time_max_seconds{namespace=\"$namespace\"}[5m])",
     "legendFormat": "Maximum ({{pod}})"
    }
   ]
  },
  { "title": "JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "JVM Heap Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(base_memory_usedHeap_bytes{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM GC Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(base_gc_time_total_seconds{namespace=\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM GC Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(base_gc_total{namespace=\"$namespace\"}[5m])) by (pod,name)",
     "legendFormat": "{{name}} ({{pod}})"
    }
   ]
  }
 ]
}