apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dest-docker-config
  namespace: product-catalog-cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCIhqecl+pahAItCMa9IzLxRBlfLOB6pEhhAljK5XOW2q7Cy3upTS0mEuHZy6h1pMiUpqJgw8OIOmxKcxveYZNFndfTjcX7v9fbdy6YiF2HRuR0/pgqk/R1PKxnj/sKhX5gi0ETBpGVdBH5LhR7THXgEPNC1NiPIdLlr/0rqjqssEbYUPjFefnrBo6CAASPR81enYFC3igjCpiPMlBnHeBp3L/YqOML3Py/AoLq6brZA9QF/NatihDYp4DINQJej4JUeq9g5GkDXdCSCHYcNeE/alQZZjj2c6YLJaku30CUxRZB3hLeREw4pW049lr9tYUbmJksKNjiQQYSFBMlKnfdtJaM5QiSqZPZokEXvCK2XAIKPn2vMNTpSqMtw63bpcinG7AV8X7RamohWUfcM1mA4LgJq9m8vYKL+7pfDUQ4Eabc8zkitTdWoA8eQ3Gqg4GQlYByMl7ag4W68Mrq8HU3S3ybomHnMgs/21+relbT6WxjYtPSgWyjig+ZsVasHahCLkI5g7m+ZU1igsKW0VXouVQ/W44QJ2VGsaxpEY6hCfLtdj1o84SLuiY1K6+txbnwEt25QOauQdCA9Ksw0EeCHWuSLlIDVQTvUdq+6UchkCBoZpgo04/9pEhZPbRyRPuAzPHwTpNsuT7WWZ6EdnO6Fg7ITJllfVYrRl5DPeHgy8FS5jAIgBif0/H51db3rRNPDKvhBkTlXZIGmPmh1Kq3z7TSZULJprW6iOSeLrLww/Zq4ji5PHqbwwfpvnn4TKbSzB8h7Qotv9gYVdrxIb8B0Q1NOwnxoPvMXHLuDCU9GyCOjLKH6KeHjonySOFFNNtgfkavOiSbgqdv6ktVwNhGK+ZZ26O4Vwt5s3IFEEF+GIDr0VmuhK2dtJeuFjn3L5X1+0obL+ONk61XcWR2LXbI1ZgOVnFB27EqyDZjAdM6suVCbTmhwuSVLdvHJyE0PzyOth2qtTaMwc+Bdlu4qHAT4QkxFz1X8I34vzi3RHC7XJhnPg==
  template:
    data: null
    metadata:
      name: dest-docker-config
      namespace: product-catalog-cicd
    type: kubernetes.io/dockerconfigjson

