apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github
  namespace: product-catalog-cicd
spec:
  encryptedData:
    token: AgBtkndIdH5lyCOTudpPz3W47Vi152MGOYwlvwj/+fddGtzi0VJFUExTtTilpX+T4FCVaDr6RcY+GJILgL+ZOIPWZ7WbY40OniLoRg32fxyO1U7BtdKbQoeEnSdjsOa4d0wAL6nZQAi7NakWH4HiYSiYa73yaITj4U39ce8oXGO8+WAiaH3mORQexCr1ZQGkte8RCa1JlOowFQLjg09e53AIOMsL9x3C6/HNOhQEcv4WURINd7rs/u0tK9EdovQT4d3Txg4Yi6J9nLaotsoUJv0JkvEqs3W2cbISMZdKG19pkaAT0gBCZYZFJHktQRAR6KHVxhrJv9DkZsDwTV9DP8e3ScJaIdD3sU3w+Ggsz5RwM0ZAGH7nv0S4m4N8PtM6GD6758wt1tsq5D+BHG+Wm5nejnvbjM2H1KsS5VZYtIVCnXAwQVUh4Nrb/7xQE6gnwaqjjqwHPADBfLQtCNVIL3XX5Z+Jg37px0evgbgDP/z5IEfcmtwPiYOdc6OFNTZXR8TAwbqpdxQH/2KEKi8ZmimHkglmvmfe5omlcju6GEBhxAU83gx8r08GFqTEnsbP0/mZeWiAuZCa392BcNr1RD6331dShBWTdTjKVr9kybxzR5GW7y/Vjfe5sGvjgbkjYdcxwuxyaSVgl4x8x7GFXflkq3A1h/3SjIuNC9+JByGZwaQnM9BNuQNjqliDI+8b/TOW0kIZkZIf2FKv1fRxomwnSnGo+vhPX+CJOG9AWLzsHsJDv4bFrtXI
    user: AgCXDrmVHVJQdKoi1EY61L5BxcWO6aIfV9EDiyhgt5J3v/B2IE4A748LcftcIYGAoIlDI0aeBVDb1Ud5FvK1/ixabLyRCsUKqdEQ1Zo3rEzoUFm5mBJeEAexHbNQyFx91cQgL5gz3+sNbjsi9jbDDOqXTAwM0yLFnxhBZiID6XBOPLdfrHTfRq7IhFIzOJ5GTbvkkfygFkXf7U59GR8mYYsu3jJRdYs4KHUuVTh+a1UU0BuzffyuhfEdg32uVSCemltwzt/fsRI21LTp/OalI/9/dukeZsAaTMarQA1pHMLn3lodj33TDu1bCMEWaj+AXGWzoXFfUfI0jAHjAvutltbnLSi4qvHGzgYeP3qeXRaGc2LgdRbzLny0uGZfFuCOkDRANxi1myfzOvBMg01afMEkbVp8aj8m6B1Wy3oP4Wk+Lz6LewJbO5VhVlBLtSKdWOZf2YqWrSINejdJ5kMizIW7s6yaVyUDzQW4F3TtxwksP87QaWDhka+kkr0M4VP8pHI+k26usc7JkDlxSO4IG2zCLUZizZrXg8mQtDL/LYih4PQGUlwbN2VAEzjpnbq5+vIJhop3SRf/uXkpdFD8augzgGQz0Xb1cT68sX/QGFhyF9V0FBOMmu8C+6+vrw8UqANCYC6IGd7gMsu9FHzW2NjA4lHXuJuA6cw48i0hoo7yiQyksLq6wINa/e+dZTLReyqqNZ476oAiFFzX0Z1t
  template:
    data: null
    metadata:
      name: github
      namespace: product-catalog-cicd
    type: Opaque

