apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-deployments-webhook
  namespace: product-catalog-cicd
spec:
  encryptedData:
    url: AgAXpH3tFScsp6k7t0zKGPsSLSZ3Z/eEeNwaxGjTnHiUE2kODuckLlWC8KissEs2G2Jm5oYsQ/LBtMlsraixZbb/dN5oEhCYVwhHSO7w284ebSdf8YvbQfSm57QEwerY47iuiPNO9FS5ZCxOVlJJ3BY1zX7db+EBrjcUBZReUThxsTpnln/FSC94OzMO2npJfRLXAHqu5sbfcr60E/aOHXezCsjwjcYhzvjLbtWmCJJIWoJUgbUW3scMzRLH1xfedf38ahapIpIo2i7uhIb3ufZkObCRoQ0Picau8NhIHzNlGURzEHKarriZhnn1+DvDYNClCYVzfvaQ/R5rnSuHKWk9OiKo80iYW+GEPzUUXzP9Lp0LXnDRNym/aNf0u713LP9+JQ0A+TV0jtQxXObgjqvOuLNpJDc6yz/bZdNgDqcIvZFeRiifnZz1rHX7zn6dyhgUBb5m+1ZcStyXruThawIvdIRppinyWW9ng07lKBxpowHC1rjqSaNUGJG9s3FGSor+eue8jLChh15LFQUnghVz2SNfh93/jumUsMQwHG31v1VMrn6u4GYW1D/sW2FVBKNYT0el6ovgOOobaeVlr8BAXk4vP3E+vr+z5uRLmyOB0uSrTcHKaZLKpL+rFGfcAynA9SF08vY333ERdoYcN9mL88ucoa/zapv/TzHaJrNcznqFRHflJIS4S59fnxQ2rct/Sx2WqHUp6Xa8JV6MnCDNDzQeZ2rAYq8dC6jMk2QVOvEtt1b3brZIepWLuQiQWVkMNJXwhhkEZHhAe1EvYBdeQe73e0NeB0EvISWcZkzMSxI=
  template:
    data: null
    metadata:
      name: slack-deployments-webhook
      namespace: product-catalog-cicd

