apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
  generateName: client-
spec:
  pipelineRef:
    name: client
  params:
    - name: MAVEN_MIRROR_URL
      value: http://nexus:8081/content/groups/public/
    - name: push-to-prod
      value: "true"
    - name: environment_gitops_path
      value: product-catalog/environments/overlays/prod
  workspaces:
  - name: git-source
    persistentVolumeClaim:
      claimName: client-source