apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
  generateName: client-
spec:
  pipelineRef:
    name: client
  params:
    - name: push-to-prod
      value: "true"
    - name: environment_gitops_path
      value: product-catalog/environments/overlays/prod
    - name: git_url
      value: https://github.com/luisarizmendi/product-catalog-client
    - name: image_dest_url
      value: quay.io/luisarizmendi/product-catalog-client
  workspaces:
  - name: git-source
    persistentVolumeClaim:
      claimName: client-source