apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- amq-operator-subscription.yaml
- amq-broker.yaml
- iot-consumer-deployment.yaml
- iot-consumer-is.yaml
- iot-consumer-route.yaml
- iot-consumer-svc.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/part-of: manuela

configMapGenerator:
- name: iot-consumer-configmap
  envs:
  - iot-consumer-configmap.properties
