apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iot-anomaly-detection-gitrepos
spec:
  resources:
    requests:
      storage: 128Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany