
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: build-and-test-frontend-listener-interceptor
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
 serviceAccountName: pipeline
 triggers:
   - name: GitHub-listener
     bindings:
       - ref: build-and-test-triggerbinding
     template:
      ref: build-and-test-triggertemplate-frontend
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: build-and-test-frontend-webhook
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: build-and-test-frontend-listener-interceptor
spec:
  port:
    targetPort: http-listener
  to:
    kind: "Service"
    name: el-build-and-test-frontend-listener-interceptor
    weight: 100