apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-and-test-triggertemplate
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
 params:
 - name: gitrepository
 - name: gitid
 resourcetemplates:
 - apiVersion: tekton.dev/v1beta1
   kind: PipelineRun
   metadata:
     generateName: build-and-test-
     namespace: manuela-cicd
     labels:
       app: manuela
       tekton.dev/pipeline: build-and-test
   spec:
     params:
       - name: PROJECT_DEV
         value: analysis-test
       - name: IMAGE_TAG
         value: $(tt.params.gitid)
       - name: git-repository
         value: http://gitea:3000/$(tt.params.gitrepository)
       - name: app-name
         value: manuela
       - name: title
         value: "Pull-request for revision id $(tt.params.gitid)"
     pipelineRef:
       name: analysis-build-pipeline
     serviceAccountName: pipeline
     timeout: 1h0m0s
     workspaces:
       - name: shared-workspace
         persistentVolumeClaim:
           claimName: manuela-shared-workspace-build
       - configMap:
           name: maven-settings
         name: maven-settings
       - name: maven-local-repo
         persistentVolumeClaim:
           claimName: manuela-maven-local-repo