apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
  generateName: server-push-prod-pr-
spec:
  serviceAccountName: github-pipeline
  pipelineRef:
    name: push-prod-pr
  params:
    - name: image_dest_tag
      value: 70c18ae-366596219
    - name: image_dest_url
      value: quay.io/luisarizmendi/product-catalog-server
    - name: environment_gitops_path
      value: environments/overlays/prod
    - name: app
      value: server
  workspaces:
  - name: git-source
    persistentVolumeClaim:
      claimName: manifest-source