apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-env
  namespace: manuela-cicd
spec:
  encryptedData:
    ARGOCD_PASSWORD: AgA9l8Fm9/c2icyHHcisZ5QUkPz5Ksq5jZFq4X8KF3bGhB/3TlD0U0+YLQWCCCOlKc+Yek0xs+I5FM+Pfnq6pzt6OIhGESHNTzABwhXz26MpKEkIbpggn3d7zSe4gcrJu1KcyryICezyZnSYyE9zTTfVU5paVPFG/91UyaKGP+iPZzMsLAIIsa0TEddqQOeSzalFAlwZdFmXXx/UyPmsOSuK3Wc/Cp+jGgs3hmY6WKBqxyRhSRSzgP72gfNOZFo+blFt4E+DyMCu70LlTi2wWbNs5fALFOKv2dNLaT0MxJETVdjBzTtI/1WlsCiKpN4ei8FYOiMBDOtflW/VqsqCWBfiK91aXlsdejc1V6GL1K/FSG6BH3yC9z7xxQ10JBzzRb+ni0gXnpWscPNo/1XqGCqsTtoyP3/RFK1b8BnzuJbJKAAN3Rl7gCvb+LMWWfQ77hPo5O4/BTDup7ezoLLR3Bq1CrHsaGEYYwQx5FJXF2ulm5INt3nF7qZe5pERkjMRoQ+Gj9J9wZkayo1qnZInljHhvcZCycCVJFVEVLpvrp2czMnSkujLJQIdTko0Cip8ZMiZTiMp4n4YxCWYJwGTK2qYqRjKkWEBPMpjA5KrFq+uiZhYrQTrDu+spSYH37KzvgAoOBrlARyIhX9ocOqPPUc3BUCxp7FpzotFJXdpmtiCd+5N+i3NdYbv0xqD6sQWxBkUqAbtQdygBi19Kd97+8CdO1EQkGYcbzTfcmiUl9uW/Q==
    ARGOCD_USERNAME: AgBs29J0lzIaW+eFcY/WyDu07+oPJ05WGchA+5zljP1/ZQnwBTblDq7N1DlgAgmtAxFPPkunABhKTF+CJbJX5JxI6/l6tgGgIF8tpCCCvMJZZHWxj+U3W97jTWjwRX4Tmq/lrfYeMO4mQPP3gErlwWmAGO7PzY8EDoPbD4jHPoCXZDGMKBpuXDAmMHcsctpHFxg17FjSq0AGz2rNGBeCGnywd0t/g7WK00zBmMM3eDt45meCDcYwuCiyor6aNvp88pElbMEDGNdp4Q7he2E+cj9sIaLwt/44/w3EFQMNmMU2IkV5PQXemx+W9uetrEuQ3wPiNgkkL8yi5OYOC+7xK5DWSwUTTMSpT+7O1nd6R7MHTc4zgZPd5nbhFOgTNDBKZkB3wIwim6vwztF3nUTMfrzA2RHUSXSS3JE7I+NUQgJjZENQ+LZoBi06TJMMgt5OkoktuNw2vGyw5r2LDuaBZGRpUgKjpdMSNlMrhMql91Tr3tuV/AEIxmel4MNXVw9d2Nb9U5e+pwX3UI5mvbPsgsEFcnRCLR6/zZ9JyGovc0lj/aNaMZYXmiUZvp1Y9/wHPq5SXSzt+GhNJ5EpmKnb4yVkxIHe+SQSwGeUEtV/YCrNE3XSBadKP4WOBhpK670kN242JBUOq6Iunix8XUz6O/11vPpQTCe6H8/6+CS9rUQSp0+ed2LNODaPSas0840Tr74Nw6kTzg==
  template:
    data: null
    metadata:
      name: argocd-env
      namespace: manuela-cicd

