apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-env
  namespace: manuela-cicd
spec:
  encryptedData:
    ARGOCD_PASSWORD: AgB98gE7m0rQkg2u6DNSFLK1tKAa5elKabc+E8KjPTnt6bvJYlmuWnPGHJ35dYXEZmXC5ShE4dxLgVOW7/FmUFrjzlKDy3xWlV7yhTenPLuXEbfB6wd8sTf8tASq258NWPm7GHFsNdkx6f6dtuWCX2TQgtr+csN3q23dNAnYa67qRIthvDPYpIzrLzVVsQlbh3LOOCiWpY7YDmTtUaiUqLzUiZrD3wnQ9v5PrsMixmgmD1GsGOr5l7i2UxAPPDIAvMRxRjlI8IrPmnRdEPoMhCFAfjcPV3NQWnrPnmxSehdj7VOjSouXigRBderxQVimdQZ3aN7mSiJeH1z9SDf6esiot1eBJA7xFCJ4CLXqTFOQQROqNQREla0DfuwSGTg04hFnPtPym6NXy1or9A/XwYZ5U3ure5XDFuFfwe6pE1WS9984CnnFdKdL3m2Ih/2np/MJBSsE16r0IF/Z8iREy77ylACoc7dObdmUqzRbdnvvsmjb3hgPONfTYa75q6wbe+RgIKzB1KNLW/Xcvb5fNJ4h07i6HDJ6J4k+Adf6iztCyZ8E8QnMtXoYrkW2b9bwS8BcuzLS13dlqHWBJtayK6U++5apj1oiBirtVgjxjOztU580NaHyzgNvue/7NhfamxcWMEW3c+V2O2hXSCmpIFfcNGDgiYItAcTc72BVEkRILKx+SYwzMWX6+ube0azRodF57YeonjnPwOT2m587SiBTCuVXyJtfSs5QtXcHbRV8uA==
    ARGOCD_USERNAME: AgBAKuwIQjyOI9iR6kjeqRLrgkKr5E8HYSC/W+q+7PoyTc8JI1XS031D3GZgisdWXH03h4Z6CToJ9xMcNlj5ii+iMws93m6GQCHmqrXzk/PZr+iuI+1ugEU5HfX3bQzzunNXVPity2BNELIpFguylGITLEomKV9WbnR69x6UvoTMkVqpoQgniA9gq92xUtirs/6CihBfMSzbGM0P0GrdD07ow2U97FrO4rXFB2effTnI1xOztcjLN6s/7PmDDnrHnThzfl0658T7MlAjjEQC4eks2fWASe6ojXHtWWX8em296a0hF2/4v/5cXA5Ngxzg0N0gM91ergUw2WBIIEI+ard1Abi7gwrj6EpMIc1hLz1yo0kElY9brLHIFWKPyjI9G2wimHxfqJ1+W4l54V+dcXaOnbIxeYNG9hYX3Qb8mlViOkEkyzAaX+SBfZprd45O9KQYFt49LNBttc6LiMmSagUYwREygeaNfYxtuGKF3EPQVm3k3FZDg4LjYl8b53P8sQ5+Y/mG8zp66JmXFLyXkEFa1kUblOwkJhNsbPU4zgUpCidWYDnMy4+XJOfJRrK/wHQ0YhZWdlORdwWPhC4WHGAXVyGlitrNWzAiikcYu7BwTTRddKbgYMTMCQN8JyROTPS/DuephG9Y/NuQwsi1+B45zUa7BgEPzCOJuKvt8RPzIQ4CyIq6yG52/pyITJNa3sk8+1IJHA==
  template:
    data: null
    metadata:
      name: argocd-env
      namespace: manuela-cicd

