apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github
  namespace: manuela-cicd
spec:
  encryptedData:
    token: AgCmtTk7DljeOgJ1wfqyAYO7/YGeCUel2rB6u/CkKQCqg1KlKTjEkOYEIA5EpJdvwdL6ITuy0e+QCe/qhEyM5jHgcfN0tC+nYDb5hZdEmJWnV28+z2TN+sFUG3d5te1zEWYH7bVgWmxeIkICma14nnAtkWC15LA+sSziRLzAIljBQhWiC4OdwqEltVadGT84V3q0zJlRhe+bptfex+7l8RQdWafh0SIPrIOCCLdJdBBljjKpAb35wqzVQLUKk5xTt7ZZQZ0nZenxjdZbv4AoO90gw9/7wBDcgLYw6tnUwFNkt3DPfz7IskENjX8URXcZDOO2YdmaRXc7kUQlJzlltkh4zXgLNwmMGdYiHM36P1FKT3P1GwC4Hl/Urh+sHssfdoK/PCpjYx2yHVKS9loRbT65RMSm698cVXZTHKbauLUzIvEq2wrpqrwAs06wuNx9J7sAyEo3b6kwelAMby/UdIK5/KRs3k8LsyMcabOCxpXx+n/B+0S9/O3nUu4wONNZQSbilbi3mq71KHsWFZqEG+n80rPGFOyhEYJIeNIxfkXI2qhx9Kn3QwUsu9FRd+llxkLRBpfc6WHQZkE7hu1REz08+SB29z37oT8VUDpeP5QtToKWXCea6SM3q39GDD8yjEr7Jrux352oeHMC7AKY51cJ72o99azeh6xiqhdaEs6F6gRywiy9NccB3FQVDfTk1JBrt+hOoZQT2zrMU/jvExne/sb14T3+ywwJS5Udk2bXZlme0lXq9KBc
    user: AgCpUJFPz/4dN5mhf9Ng4cxRMT6rs02c4p4z/CuWzuGiPxbWq8lpJf6unzRFTNsNQlGnBn+xlbQ19x1unIvxMPYDdI8kv95gGoXxISQ1hSZ7EUaubrqxaldaYKEtoMQ9uZNTVVM7OWfhZCoZIqzGduP5C94rme/6vKYpETXSFQf94vFsvrqZxxX9HmtMf2yX1Wn7yRcpP+YDU3K5/kPjpDiBMJHUlUFIykYKYkqYvT5re4US4VHi0LwWPY6TUwRKIGwEP57RMR/TrnfeyV/MvJB85eaSn2yKlqsX97AaR7cPOG7kZ78V9SkusdKomRguOvkXGWlnZQYzWEGQia7ssXG5cwhGFBePCQktUwuCgOlSMKUypLJjabDh3xxLoEPJKy1dR2+JpyKlZ2J6+keFHuZ8lFWuE7XxuMr1D4K8fD+/EtSRtXTPV2X9XY0Tg1NijMEY21wnTLrBAPyaHJ9jt3XTFfahALp0SoJHlvU7QiPqxFaekdeXter5E11NceTWYumrpxOD9F4ueLBVuDwyrBRmsprKcb/Eq2VPx0ZogEmhVri6mDL8qLN7eazk/X9z6SZZw9aaHi5OLxX2s+USxscfWD6vnK78btOO09poL37D3P3+rBF5H2N8Vipgk75Wt346QTD1LSGEspFGXu3C5dcH9roYombv3FeS8zIXjIObxCsdf+QxOKhyjvQUbXLZeXJ9QokH0fevmNnHHXrd
  template:
    data: null
    metadata:
      name: github
      namespace: manuela-cicd
    type: Opaque

