apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    application: anomaly-detection
    app.kubernetes.io/part-of: manuela
  name: anomaly-detection
spec:
  lookupPolicy:
    local: false
  tags: []
