apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: seldon-operator-certified
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  channel: stable
  installPlanApproval: Manual
  name: seldon-operator-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: seldon-operator.v1.7.0
