apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: iot-frontend
spec:
  tags:
  - name: 0.3.1-12
    from:
      kind: DockerImage
      name: quay.io/luisarizmendi/iot-frontend:0.3.1-12
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-14
    from:
      kind: DockerImage
      name: quay.io/luisarizmendi/iot-frontend:0.3.1-14
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-16
    from:
      kind: DockerImage
      name: quay.io/luisarizmendi/iot-frontend:0.3.1-16
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-20
    from:
      kind: DockerImage
      name: quay.io/luisarizmendi/iot-frontend:0.3.1-20
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-21
    from:
      kind: DockerImage
      name: quay.io/luisarizmendi/iot-frontend:0.3.1-21
    importPolicy: {}
    referencePolicy:
      type: Local
