apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-catalog-prod

resources:
- product-catalog-prod-namespace.yaml
- ../../../components/apps/database/base
- ../../../components/apps/server/base
- ../../../components/apps/client/base
- post-sync-pipeline-job.yaml


  
images:
- name: quay.io/luisarizmendi/product-catalog-client
  newName: quay.io/luisarizmendi/product-catalog-client
  newTag: 49c1a5c-2068611703
- name: quay.io/luisarizmendi/product-catalog-server
  newName: quay.io/luisarizmendi/product-catalog-server
  newTag: 813e347-3928055513
