apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: anomaly-detection
spec:
  tags:
  - name: 0.3.1-10
    from:
      kind: DockerImage
      name: quay.io/luisarizmendi/iot-anomaly-detection:0.3.1-10
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-12
    from:
      kind: DockerImage
      name: quay.io/luisarizmendi/iot-anomaly-detection:0.3.1-12
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-14
    from:
      kind: DockerImage
      name: quay.io/luisarizmendi/iot-anomaly-detection:0.3.1-14
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-17
    from:
      kind: DockerImage
      name: quay.io/luisarizmendi/iot-anomaly-detection:0.3.1-17
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-18
    from:
      kind: DockerImage
      name: quay.io/luisarizmendi/iot-anomaly-detection:0.3.1-18
    importPolicy: {}
    referencePolicy:
      type: Local
