apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: seed
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  workspaces:
  - name: gitrepos 
  - name: config
  - name: github-secret
  - name: argocd-env-secret
  - name: quay-secret
  - name: build-artifacts

  tasks:
  - name: git-clone-dev-frontend
    taskRef:
      name: git-clone-with-tags
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: config
      workspace: config
    params:
    - name: url_configmapkey
      value: IOT_FRONTEND_GIT_DEV_REPO_URL
    - name: revision
      value: master
    - name: subdirectory
      value: dev/iot-frontend
    - name: deleteExisting
      value: "true"


  - name: git-clone-dev-consumer
    taskRef:
      name: git-clone-with-tags
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: config
      workspace: config
    params:
    - name: url_configmapkey
      value: IOT_CONSUMER_GIT_DEV_REPO_URL
    - name: revision
      value: master
    - name: subdirectory
      value: dev/iot-consumer
    - name: deleteExisting
      value: "true"

  - name: git-clone-dev-swsensor
    taskRef:
      name: git-clone-with-tags
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: config
      workspace: config
    params:
    - name: url_configmapkey
      value: IOT_SWSENSOR_GIT_DEV_REPO_URL
    - name: revision
      value: master
    - name: subdirectory
      value: dev/iot-software-sensor
    - name: deleteExisting
      value: "true"

  - name: git-clone-dev-anomaly-detector
    taskRef:
      name: git-clone-with-tags
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: config
      workspace: config
    params:
    - name: url_configmapkey
      value: IOT_ANOMALY_GIT_DEV_REPO_URL
    - name: revision
      value: master
    - name: subdirectory
      value: dev/iot-anomaly-detection
    - name: deleteExisting
      value: "true"

  - name: git-clone-ops
    taskRef:
      name: git-clone-with-tags
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: config
      workspace: config
    params:
    - name: url_configmapkey
      value: GIT_OPS_REPO_TEST_URL
    - name: revision
      value: master
    - name: subdirectory
      value: ops
    - name: deleteExisting
      value: "true"

  - name: bump-build-version-iot-frontend
    taskRef:
      name: bumpversion
    runAfter:
    - git-clone-dev-frontend
    - git-clone-ops
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    params:
    - name: component_name
      value: iot-frontend
    - name: subdirectory
      value: dev/iot-frontend
    - name: version_file_path
      value: VERSION

  - name: bump-build-version-iot-consumer
    taskRef:
      name: bumpversion
    runAfter:
    - git-clone-dev-consumer
    - git-clone-ops
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    params:
    - name: component_name
      value: iot-consumer
    - name: subdirectory
      value: dev/iot-consumer
    - name: version_file_path
      value: VERSION

  - name: bump-build-version-iot-anomaly
    taskRef:
      name: bumpversion
    runAfter:
    - git-clone-dev-anomaly-detector
    - git-clone-ops
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    params:
    - name: component_name
      value: iot-anomaly
    - name: subdirectory
      value: dev/iot-anomaly-detection
    - name: version_file_path
      value: VERSION

  - name: bump-build-version-iot-software-sensor
    taskRef:
      name: bumpversion
    runAfter:
    - git-clone-dev-swsensor
    - git-clone-ops
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    params:
    - name: component_name
      value: iot-swsensor
    - name: subdirectory
      value: dev/iot-software-sensor
    - name: version_file_path
      value: VERSION

  - name: s2i-build-iot-frontend
    taskRef:
      name: s2i
    runAfter:
    - bump-build-version-iot-frontend
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: build-artifacts
      workspace: build-artifacts
    params:
    - name: TLSVERIFY
      value: "false"
    - name: PATH_CONTEXT
      value: .
    - name: BUILDER_IMAGE
      value: quay.io/luisarizmendi/ubi8-s2i-web-app
    - name: CHAINED_BUILD_DOCKERFILE
      value: "FROM quay.io/luisarizmendi/httpd-ionic\nCOPY --from=0 /opt/app-root/output /var/www/html/"
    - name: TAG
      value: $(tasks.bump-build-version-iot-frontend.results.image-tag)
    - name: OUTPUT_IMAGE
      value: image-registry.openshift-image-registry.svc:5000/manuela-test/iot-frontend

  - name: s2i-build-iot-consumer
    taskRef:
      name: s2i
    runAfter:
    - bump-build-version-iot-consumer
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: build-artifacts
      workspace: build-artifacts
    params:
    - name: TLSVERIFY
      value: "false"
    - name: PATH_CONTEXT
      value: .
    - name: BUILDER_IMAGE
      value: registry.access.redhat.com/rhscl/nodejs-10-rhel7
    - name: TAG
      value: $(tasks.bump-build-version-iot-consumer.results.image-tag)
    - name: OUTPUT_IMAGE
      value: image-registry.openshift-image-registry.svc:5000/manuela-test/iot-consumer

  - name: s2i-build-iot-anomaly
    taskRef:
      name: s2i
    runAfter:
    - bump-build-version-iot-anomaly
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: build-artifacts
      workspace: build-artifacts
    params:
    - name: TLSVERIFY
      value: "false"
    - name: PATH_CONTEXT
      value: .
    - name: BUILDER_IMAGE
      value: registry.access.redhat.com/rhscl/python-36-rhel7
    - name: TAG
      value: $(tasks.bump-build-version-iot-anomaly.results.image-tag)
    - name: OUTPUT_IMAGE
      value: image-registry.openshift-image-registry.svc:5000/manuela-test/iot-anomaly-detection

  - name: s2i-build-iot-software-sensor
    taskRef:
      name: s2i
    runAfter:
    - bump-build-version-iot-software-sensor
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: build-artifacts
      workspace: build-artifacts
    params:
    - name: TLSVERIFY
      value: "false"
    - name: PATH_CONTEXT
      value: .
    - name: BUILDER_IMAGE
      value: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
    - name: TAG
      value: $(tasks.bump-build-version-iot-software-sensor.results.image-tag)
    - name: OUTPUT_IMAGE
      value: image-registry.openshift-image-registry.svc:5000/manuela-test/iot-software-sensor

  - name: push-dev-tag-iot-frontend
    taskRef:
      name: github-push
    runAfter:
    - s2i-build-iot-frontend
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: github-secret
      workspace: github-secret
    params:
    - name: PUSH_FLAGS
      value: origin $(tasks.bump-build-version-iot-frontend.results.git-tag) $(tasks.bump-build-version-iot-consumer.results.git-tag) $(tasks.bump-build-version-iot-anomaly.results.git-tag) $(tasks.bump-build-version-iot-software-sensor.results.git-tag)
    - name: subdirectory
      value: dev/iot-frontend

  - name: push-dev-tag-iot-consumer
    taskRef:
      name: github-push
    runAfter:
    - s2i-build-iot-consumer
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: github-secret
      workspace: github-secret
    params:
    - name: PUSH_FLAGS
      value: origin $(tasks.bump-build-version-iot-frontend.results.git-tag) $(tasks.bump-build-version-iot-consumer.results.git-tag) $(tasks.bump-build-version-iot-anomaly.results.git-tag) $(tasks.bump-build-version-iot-software-sensor.results.git-tag)
    - name: subdirectory
      value: dev/iot-consumer


  - name: push-dev-tag-iot-anomaly
    taskRef:
      name: github-push
    runAfter:
    - s2i-build-iot-anomaly
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: github-secret
      workspace: github-secret
    params:
    - name: PUSH_FLAGS
      value: origin $(tasks.bump-build-version-iot-frontend.results.git-tag) $(tasks.bump-build-version-iot-consumer.results.git-tag) $(tasks.bump-build-version-iot-anomaly.results.git-tag) $(tasks.bump-build-version-iot-software-sensor.results.git-tag)
    - name: subdirectory
      value: dev/iot-anomaly


  - name: push-dev-tag-iot-software-sensor
    taskRef:
      name: github-push
    runAfter:
    - s2i-build-iot-software-sensor
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: github-secret
      workspace: github-secret
    params:
    - name: PUSH_FLAGS
      value: origin $(tasks.bump-build-version-iot-frontend.results.git-tag) $(tasks.bump-build-version-iot-consumer.results.git-tag) $(tasks.bump-build-version-iot-anomaly.results.git-tag) $(tasks.bump-build-version-iot-software-sensor.results.git-tag)
    - name: subdirectory
      value: dev/iot-software-sensor


  - name: copy-image-to-remote-registry-iot-frontend
    taskRef:
      name: skopeo-copy
    runAfter: 
    - s2i-build-iot-frontend
    workspaces:
    - name: config
      workspace: config
    - name: pushsecret
      workspace: quay-secret
    params:
    - name: TAG
      value: $(tasks.bump-build-version-iot-frontend.results.image-tag)
    - name: SOURCE_IMAGE
      value: image-registry.openshift-image-registry.svc:5000/manuela-test/iot-frontend
    - name: TARGET_IMAGE_CONFIGMAPKEY
      value: IOT_FRONTEND_REMOTE_IMAGE

  - name: copy-image-to-remote-registry-iot-consumer
    taskRef:
      name: skopeo-copy
    runAfter: 
    - s2i-build-iot-consumer
    workspaces:
    - name: config
      workspace: config
    - name: pushsecret
      workspace: quay-secret
    params:
    - name: TAG
      value: $(tasks.bump-build-version-iot-consumer.results.image-tag)
    - name: SOURCE_IMAGE
      value: image-registry.openshift-image-registry.svc:5000/manuela-test/iot-consumer
    - name: TARGET_IMAGE_CONFIGMAPKEY
      value: IOT_CONSUMER_REMOTE_IMAGE

  - name: copy-image-to-remote-registry-iot-anomaly
    taskRef:
      name: skopeo-copy
    runAfter: 
    - s2i-build-iot-anomaly
    workspaces:
    - name: config
      workspace: config
    - name: pushsecret
      workspace: quay-secret
    params:
    - name: TAG
      value: $(tasks.bump-build-version-iot-anomaly.results.image-tag)
    - name: SOURCE_IMAGE
      value: image-registry.openshift-image-registry.svc:5000/manuela-test/iot-anomaly-detection
    - name: TARGET_IMAGE_CONFIGMAPKEY
      value: IOT_ANOMALY_REMOTE_IMAGE

  - name: copy-image-to-remote-registry-iot-software-sensor
    taskRef:
      name: skopeo-copy
    runAfter: 
    - s2i-build-iot-software-sensor
    workspaces:
    - name: config
      workspace: config
    - name: pushsecret
      workspace: quay-secret
    params:
    - name: TAG
      value: $(tasks.bump-build-version-iot-software-sensor.results.image-tag)
    - name: SOURCE_IMAGE
      value: image-registry.openshift-image-registry.svc:5000/manuela-test/iot-software-sensor
    - name: TARGET_IMAGE_CONFIGMAPKEY
      value: IOT_SWSENSOR_REMOTE_IMAGE

  - name: modify-ops-test-iot-frontend
    taskRef:
      name: gitops-imagetag
    runAfter:
    - git-clone-ops
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: config
      workspace: config
    params:
    - name: CONFIGMAP_PREFIX
      value: IOT_FRONTEND
    - name: ENVIRONMENT
      value: TEST
    - name: TAG
      value: $(tasks.bump-build-version-iot-frontend.results.image-tag)
    - name: subdirectory
      value: ops

  - name: modify-ops-test-iot-consumer
    taskRef:
      name: gitops-imagetag
    runAfter:
    - modify-ops-test-iot-frontend
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: config
      workspace: config
    params:
    - name: CONFIGMAP_PREFIX
      value: IOT_CONSUMER
    - name: ENVIRONMENT
      value: TEST
    - name: TAG
      value: $(tasks.bump-build-version-iot-consumer.results.image-tag)
    - name: subdirectory
      value: ops

  - name: modify-ops-test-iot-anomaly
    taskRef:
      name: gitops-imagetag
    runAfter:
    - modify-ops-test-iot-consumer
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: config
      workspace: config
    params:
    - name: CONFIGMAP_PREFIX
      value: IOT_ANOMALY
    - name: ENVIRONMENT
      value: TEST
    - name: TAG
      value: $(tasks.bump-build-version-iot-anomaly.results.image-tag)
    - name: subdirectory
      value: ops

  - name: modify-ops-test-iot-software-sensor
    taskRef:
      name: gitops-imagetag
    runAfter: 
    - modify-ops-test-iot-anomaly
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: config
      workspace: config
    params:
    - name: CONFIGMAP_PREFIX
      value: IOT_SWSENSOR
    - name: ENVIRONMENT
      value: TEST
    - name: TAG
      value: $(tasks.bump-build-version-iot-software-sensor.results.image-tag)
    - name: subdirectory
      value: ops

  - name: modify-ops-prod-iot-frontend
    taskRef:
      name: gitops-imagetag
    runAfter:
    - modify-ops-test-iot-software-sensor
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: config
      workspace: config
    params:
    - name: CONFIGMAP_PREFIX
      value: IOT_FRONTEND
    - name: ENVIRONMENT
      value: PROD
    - name: TAG
      value: $(tasks.bump-build-version-iot-frontend.results.image-tag)
    - name: subdirectory
      value: ops

  - name: modify-ops-prod-iot-consumer
    taskRef:
      name: gitops-imagetag
    runAfter:
    - modify-ops-prod-iot-frontend
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: config
      workspace: config
    params:
    - name: CONFIGMAP_PREFIX
      value: IOT_CONSUMER
    - name: ENVIRONMENT
      value: PROD
    - name: TAG
      value: $(tasks.bump-build-version-iot-consumer.results.image-tag)
    - name: subdirectory
      value: ops

  - name: modify-ops-prod-iot-anomaly
    taskRef:
      name: gitops-imagetag
    runAfter:
    - modify-ops-prod-iot-consumer
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: config
      workspace: config
    params:
    - name: CONFIGMAP_PREFIX
      value: IOT_ANOMALY
    - name: ENVIRONMENT
      value: PROD
    - name: TAG
      value: $(tasks.bump-build-version-iot-anomaly.results.image-tag)
    - name: subdirectory
      value: ops

  - name: modify-ops-prod-iot-software-sensor
    taskRef:
      name: gitops-imagetag
    runAfter: 
    - modify-ops-prod-iot-anomaly
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: config
      workspace: config
    params:
    - name: CONFIGMAP_PREFIX
      value: IOT_SWSENSOR
    - name: ENVIRONMENT
      value: PROD
    - name: TAG
      value: $(tasks.bump-build-version-iot-software-sensor.results.image-tag)
    - name: subdirectory
      value: ops

  - name: commit-ops
    taskRef:
      name: git-commit
    runAfter:
    - modify-ops-prod-iot-frontend
    - modify-ops-prod-iot-consumer
    - modify-ops-prod-iot-anomaly
    - modify-ops-prod-iot-software-sensor
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: config 
      workspace: config
    params:
    - name: subdirectory
      value: ops

  - name: push-ops
    taskRef:
      name: github-push
    runAfter:
    - push-dev-tag-iot-frontend
    - push-dev-tag-iot-consumer
    - push-dev-tag-iot-software-sensor
    - push-dev-tag-iot-anomaly
    - commit-ops
    - copy-image-to-remote-registry-iot-frontend
    - copy-image-to-remote-registry-iot-consumer
    - copy-image-to-remote-registry-iot-software-sensor
    - copy-image-to-remote-registry-iot-anomaly
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: github-secret
      workspace: github-secret
    params:
    - name: subdirectory
      value: ops
    - name: PUSH_FLAGS
      value: --set-upstream origin master