apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-env
  namespace: manuela-cicd
spec:
  encryptedData:
    ARGOCD_PASSWORD: AgBTgIQ1QLyBLjPAAQ61paYkQc9gjNKTWaU3NyLYHS8GkarsNzefsM+oT13hbHL4EAx3q+K/16sllksIVlrUML6vaaKicimuZH9f6mTq9UnLLMNpg0fdVJA/ZBXWjHza2/03Ba2qzpIll1Dpk1POoW43JjDpIQdCqdEJNcBkzBSti3ej7rfFN46Rb2oXWKP+fnJoRToGKE1zY3yW0wXSPuOgu5pIJqdR3BOZspL/il6iQdKDFiubsR3F1y6hopBqjk7tkdZ5QAP5wNKYt+j0d/AH4KQ+PctxShMPfH+adj0EhhqdcCHyGiT0P4P8GRDDaHpDQpJA48CRKBVVKXFFkmucWQl6XSjKk6+f6d7omtkJyBhxi3MbXrEbpUBPfzTeK1eDPjxyGeIZ5nCXu8PYwKrTXIFi/DHyuxj/CmN9fyHTbu87N4bSF4w1xZzlTP9oEPoWiUalZytVTokZChfxORzNvu8VmYPYD1btwZ2ouFd4m0DWTsMbS/hw3FeQ0uj1nLmhUvHlboqthC2e6d9qCC2cHrtaih3Jap87HB8F/5mKKk16u8TnetWoYuLNtChR+rXvXHypM++PO3yPJ/IMCQ0HBhEzL7Q178eEzMaWb6YAcL8pSQ9gVT61UwyGGVOnS1bmgkNnqwo/VuEbBssRo21/UJPSMiCsjQon7SIhMTsemrqWdO09fP82F8uFeHYlIWMWj7RtgzSajWbA4jdyCdhOWtJbuglrU8Ryox1a57P0hQ==
    ARGOCD_USERNAME: AgBIm7jy+GCKmwTCXeHj9z9+Ka8fMhZ3vXpL4DX4LA7uXQ9ryh7bq5OjPRGwVkUm8E7hvo9weX4NEINI6c4OmA+ykPUHQNJOvX6rjgqXXi4FJCZktM3fICYr2pcT+uGvnK9ACzHZnLscQcNBOBcIWTT2BK8U/y9iPk4RQJoR7DKXWLFjtlblGmVGA13cNKJGNyoygryMWqdy4VrM0bxqjVJI0GCa3UoXHK2B9Ch3b7RXQdvOl1ZgoM9kN9CQQHuGkWE1Q48mEKrZNx/2icRUKV5K89fxN6H35XVP4nJpDFooTUZKk2pP6hKUp2Ll6aougcFy3UiZd6Ph8hgQC+44rq/SOJfjzeAxomReYAHQb+3Y0QoqGjteWpMA6FSKxXJvB1G7aBzvTqrBCdYvNps32guyaJW1n+MVrUp5+0F/wIPQSOmfCukW3TqrDYSEGKZ8g3ryuroEPsLItmaxjuaknTJNTgRC5+09jOmo7yj/nYcH99+PcyAE1Ca1ittas2/yaA8xKaJYCBZoaoLKfUbORAkQcTThRs0HSg3Z4q9Bt6CuN38a6mfA/A44/04ct8zTOAC+n1UTYuEw1GS5vmXvd2YhvHsDRegB3zhqq8rZwuh4ZPRmQPH/IkUxGBHcws2nX4fm4GgAWtYqeAKGKX4ZWmP30cQ0a1F8es9MxW4zGIvBGicCb92bgGADMpXXiSC8tPXqAYmz4A==
  template:
    data: null
    metadata:
      name: argocd-env
      namespace: manuela-cicd

