apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-env
  namespace: manuela-cicd
spec:
  encryptedData:
    ARGOCD_PASSWORD: AgB94XpLFjcxpvYQYLHzkKtdfhSt6ErmHSzMkwttfv/hGEMcKi2zLLUBRS4afLwp/yVs6eD2DgAPoFc2tJEUYBS13KBbFmae6fKrsxg3Kw6xFKwNO6eAHbmnspMpSKwW/s77k5H8XtkLt3GbaJyKHpIAskOO7bW924FVz+5CebYuPCt640+xh9P5zke1q5fNZIjYMZRnjesD0bLTeUJeeTtL54sgzkE/aBgA026RHIUlUzm2+IvxDWl11SkNe9y+O3oWPBJg0Z+D6EMCDL7D/B6biqiQm2JYlfQLMxNyNvect8nlGmSlSS0swvzyD14wWd8uPOMIpmqVRuEofm6xvBgopNsUcqQCEyu2SlA9YCEwhCfoaShBxelVWI27I3958A95wW5+L8L/eZW8EcW+Um4nrwJPoiOndufGaZL3wI7Gx6jWIx/ssOQFJ32975MVTwWj8f4Z0QjcxPZu8iqhf5oaOZBKMgL9HenJtrSqVqM0Byg3aZ6MZdC8LzZZ5R9WHKmNFLM/HBEbd4xdS9SarMA1sizf3uRcXzz9yTFzuPc2s1kiu3/ryn/+ifiaUg5cIv2pJYu3hwGdCOItLA5EsD8BSOI+ASRkzTFZdqo6pRAONkW3dKUBvNKvhkjRO2ct27rGmwW454AUkOchVTMn2CsxpxPx+nzML1g9MX13mGn6MkGL/XB1VQMr+N+nwmf8e1WYNvYQ7mcGFm2MCTHBdKqJdYROJZpjHGm81gDHo2eMsQ==
    ARGOCD_USERNAME: AgBXGZhW/rrvaa4IkmAeP0dqy1Tr/4npZp3SJYDb16uSaCJVsFDX8BoZsSvATFN/hauXVko5diNu9XiDwpsVdO3pwnkAA8Jqbo4RNz1DfpSN/cv7MH2l/aNI8W3dkEaFiHX+pGWPWmNcC5mC3Elp1b4deEoqlhgRmvyiOsY3MYwvIU8s6McMg7UvsaiHT3ysuPkJ6GINdxmbCIr9yZSpV2l8r+k9ow48mnscPesn94EzL7lo4+0GhqEWcEwi7mlJVmJtUpnvbMcINfupdRq+7vgppWLqvMpn+kK0y2x8wH3iLWssznj3Y13mdKc3wVFUKZEuJYFAuzim5CDbpCcylPa2PLhGFsq9aQw0o3U1ydYnM46ZGXMeyXYJTTdparLL0A7JC74qBjpGLFWI4ukxF1SmOP47YE0NGCLI8kzWledgbZjUZYnLs7fEo/uwTb/qIXMRJUuEaqRhI5BOkTjc9UNqTt/9VFNqiB4qPvZMqBYV5y2JmgJ2BJMt5ooGSuPo6Bxxwikl9SVsPrXLP5KmMPsPRNz/KxJCF+IPVx0zKLwQ1ETOlf1vAH6yEQKpukHp4jGTFnQ2Gid7xW1PVl20Z+rdKhfSc/BcbJrOikib9ba9OzNItAZ3fm4rk+LBOUM1HTIA+nbXroEGk9l4ZYQ+l2wa4HrYU+wm8ae1o9iizMKkX/FgZANj34gRxsb1+2rWBe6r28fGEg==
  template:
    data: null
    metadata:
      name: argocd-env
      namespace: manuela-cicd

