apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github
  namespace: manuela-cicd
spec:
  encryptedData:
    token: AgBlvtwVGfHpQSLW+UXlvG9aPn3ZTzfD2mNx3wb9ATJUCbJRG8xyLKLzaeWZTJjSpQGFPQ9lfXnvneWKucNmHjjsTas2rQDRywycd3DIwQGLC8GHwHaSNebdFGjVW3Xoy5O4sIBVhOplkca0f1PW1MBhbval7O2jqBYBxGvDAZ7jHczsGGWn0NBu3ANTKdTz9tvVhm/B+osCRDTp31KdB2hLrRPe2U/caqvdHzzurw3e6YVZhOcB3PuzQJL9xdR+1x7Fp2uEKESl2mGmXocxpz8oBshDcKpv3JqSdSM/dCxOV8AqAKUuDe2Um6wn95UthS4p5n2BU6nsfKzLRyeV0Z+FjelnueWglaSViunW3CgsusRZVu5iBaxxF5k4tW2y5KJSOnIpRdfy6VFFXdLcMeNeiWJn8pgpAhh8u1cHlGISw4+p6bysL77xnkWkXUvM9S1AKaV5ttWY1VQDgzzPUYLPCDrKaoCXOm0H4sfbOF/bePkbiy/j/Co1KtGKYnWdjpCWQeZRivbJvkVmGetDc2p0a3wRqh5dRUffTZ1Xo+CMEihwIKZ+5u0O5euYwtzTpZYHXzx0h2VL9LI4YkDg2tZpVSrC4uFzJhL8p99kiZthz7j/Q5G5VBweYtL815nyusiYmNhnkqy7m1kVERse66PkVi/3Udw0OmnR4GsT/W8jo0lT4FeYUqtkA7tD9XuD70jNqincdfmAH4L/QGRz9l1RKBu1SvgrENSxOREqgKFgD39dcVr46B1p
    user: AgBMuFyTg4CnQH3HJccZNRCBQEXerAu3WXCFzJOsd2RUj8OIubgLrBjPpBI7/8txp7cpWbEnJ2sGrkHS/bCRcTbbWLxHVShv/3v/Rv/Dd7imMMowm9Pn+u/24lJeQ2U3n/CvulI8kExiqz8a/cNAurKLehj+WjRqsDLbn9k8yY7UyL3gtJ6OH1QkDB5bSBCGTs8m5HKEYHMnQtgUUB/rwLYzGpy3rr5qfXjT5PMnZndaYqy/Vy1kb8uRLmidR84VdRged334+gEQel0h+B/6b0hYlLu9BZI++xevK9ywK8TkvPHyLuvYZJ7ul3u9dSLK4eQ0Bu/Dd3D16rNzTtblyVuKgRzF8H6lweiwIki2M10zqDczRXMog4JOT4uxQ/g0dvUgGgI2THeujz2/8sM8ax6nCIXu5EwtyKv0ausfOynYmOxtXL4+roEwwt8BrbP8i3bld4bQZ4/HHAhhk26KCzK0vWmObrqHHjhzFHf65tuc1jWPF3Xdof7yI8GWc38BV+mjXWS4bISgp3UkK4hUlqCwQEckz2ZWdfb962o+DGSj5IvzkUQUgGWpRdQeUnii1AWjgaXdABK6k4uGLuX0jwH8i4gI4lFLxn/Zj/Hv0Ypyun7IK2KrZfD2IatpvTm7ZQuyXQv3g6EObko7Z18LrigWGxHaTEoAroZ+8Vm4Q5oqeaaxak6IP29fmTZFQ4p5r/9zcHEJ5bgVem42+T87
  template:
    data: null
    metadata:
      name: github
      namespace: manuela-cicd
    type: Opaque

