apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: quay-build-secret
  namespace: manuela-cicd
spec:
  encryptedData:
    .dockerconfigjson: AgA49xz9dh8pcljbSm7po3OvTdLNWo06YJ3N29ieFSKHWVsMGcNOm2C9c9xZ0XwPkTYIrTQkLQDlcJt21v1EvUIn7tJaN/K6W3T76sVgnPFMkm2awTsFwdWHocyRYU/J+9NxHN5rRSGmUSSTtJtHexzDAeorTj8m8rL+u4bSAHja+2k5+JyUJ2+yD2LnvBUEuFaHvgPQz2oAhq7w640RhEcgfAHK9skBX6UB4vd5TwiuzeOOBasvFfxUilLlmi+jD/wjNkEP74inANrV8JjYDqF7sgjiECs6yjMn5zztDLD9/ekLek2JDCqaQaf9tw56HDC+Ub1F6aOgZv4lshpzkOdkzSiymNt/jkmSaOz2C2QE/ymfsRmWoOlLuAkJ9dUpoTeNQECUtv4E9uvLO8vHAcVLRNKH02xXFkl2yFAJZRkndw6wmN6b2dVA0w6fQLfiMqU9pXRNzwWCTwa1tHlzWEg9D5Eya/3YnDiMSaB42xcaTCEAkgmWfbmcDq63djzrbUEIyTmKFjAoYoWA8WRKlfgXJhgTBwIxhBJ9Qi1Np7+RSC7ZtBeXiCVJTs1+JbLOZ/bbv6eXfVE60DJBZZNvg18IHe/oa5cJLtWU4Iw9bkPYDJimEOUS2KclPBlsXtgkTE7XzIgS1X2C33TzaOVtvzWOQ4G8WQ5PeKYWAYhUFbyVK9EdRogux2DTmMTc+m9sn7QBxj9uoDXTRGHUxjdbKv5g+uTubPhffWJjRPWkgYswrU4vWcpj1kSIs/ANqXPbS7V5l9vuQa3ynqq/RHjW0JG/3kdRb+7V8J8b6Rh9rrbR75NfGG6J4peH8Ama8dmfsCXNuhJN0vwDZFefiFRFC8TsYikSA98Mh8BZfLpsUHxrvmjrQINtlmSiZQps8kVAwxP547e4zQCtvr0Nm2sm29NCUloiab9K38XrE4JExQa81OtuhQdm6Y27JEegL8hO8Z8CWcSEL2NjdZ+I6eeRBxDOZasoakHoeaAHYqHlgISAjQxEOg==
  template:
    data: null
    metadata:
      name: quay-build-secret
      namespace: manuela-cicd
    type: kubernetes.io/dockerconfigjson

