apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: quay-build-secret
  namespace: manuela-cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCO73VsgdkuAlv8GW3jfphdgTcJzXiOJwMKxESBbfPLWa1FEkGLj4s4StzCKx0q0I3Q/7Hmpyo7Nllx/FwA2nkb9xSG/Gkg0r3NsX0L4Ta5JTm5Ca+TriEk01EVPeUqGdcuzEwOM0cbXl9WbD6xnO+wYccmjh5xZbJZz3E3XXYKOm73HXFNGl5BLTi4nUDRkcASMZjKUVFcheQ0L9UG374YIJDWygKf3mnEvyugJHKhueViPDp9uusLiV3dEbRNYYrMS6JY/lZQf5CdwbUWZ5nUk3r6a6RechYq90O6aQDoH1QPTM3Smo6ralOrZWZdyyYlxPsaIAbsl9Q9ZUsnSelY0CKHxort+7Ho9lSqYB/GxHMHQD1IDW9U8wsbVPTtmxd4R3yNecWxBRXGtvGGF08w+/fVs93tr+pNGQ4MX/YU0VRvtmPg3ZjoRUq61Yc4onxluIstVprnEFKVuVe/RbUyf55l3tZNYMt2HUbljxmlsdkHdFaJQyCsHx6sRBccJPK4pPEjRz2iR8ihxucmls5u9w7FU15I+KilULI3QcrA6EGKMp/pCm/9aOKHxwHGDLES7D2D+z2YTgFQXcR9UU5ibAObCUXDOWgCqnFjygs4vb0m58x6tCs6s3x5EODMSjbYKO9gD8Nw0SmDavJwJ9EkxMThzocQPkRNDnL6hGiBvi/9PX2hzyGNELs2naK+uvPACN2bTBPMj+kvS/JWKbBUZkCnMwdk8QwUUdJGUz4YmNaFFu1wy5j3UDVuUeimo2D10MGJUhRaB/wp68gePwHs3bdCeSxp4Y3WmMfIquNaKsS/D3eDPAII29K9DbNrFhdz4MVhnNWUzm7Dh2aWo2JqFnatLn0fOwm4t2dwk7l9L3l1FWegMaDXBAEJZ9wuP6uT8y7wMS5fxe4YnbMwbZBPmytFQC3foPz6S7vTBvn+xBJhGmlJgoZkJRY2G1sNqqOI1+Zg9xOm7Q7Q+UY8DjpvyRiUj0vGZW+DXBCGGFENPWMosA==
  template:
    data: null
    metadata:
      name: quay-build-secret
      namespace: manuela-cicd
    type: kubernetes.io/dockerconfigjson

