apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: quay-build-secret
  namespace: manuela-cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCwnbBv+ceuTbdRTyZCokbd/C3BxDGmXpwXaFxB2g+/pq+BXf9WOJ+stzRgDNnDrkFamsH8klHSNN/9hEHPvCqdVx0oQ+YT3t4cg8yUwZc5ef7fOYvJU1KzefRQJaUfxDBUNIBj01SwfbCLRDobV0hB9NPbtzT0MJTfZ8IDFnyCAZ6VXY+xYfD8ANfMhLLimv0A4VeCwk1WB3fmkJdqkncLMFFWvz4viA4nu+egvXx7eKeIZ1c76T8XpYNb1W6yJIwpP/jcXAzRhxE1rvdqxZbyzAEwh1Tfv5/8/JeByB5tMmEFO4A+ovJQfkQOGMvT6BkBkeWLume+1wryPQELO8C2UZKgZVWHkQ+4EcUY1zenaGBinsxssDf5j8pnXTrOvSmF5Yn6+QBzXf5ewv0KZeDJ+kAhKOB+OkajPpnSxUkv8kAq43G+zG/E2nESH34d9fDc2eNxqKgE5A7CcQi15t62WZ6+6LuZ6kkjcjCJJsF84HferQa2+/B2LSL9ob46oLiifpahGBiRMImOTYjiSk+z9vTBt6nZL+LyJbEd2lKrKELJRSyS8xv3gAV0mud1M2qdgyN6jbjTdNj2A/OQ1WpBs6R8fIYI8XyvykFQRggR0ro2lJXsN59yZLrfQGMnWyDIkl5Iklxo36TUGWWSEewhtySfJOhlxDM71fzgP4q0gj937rbFKEmfnJ9rh2zE9D3/jM3BNa7f3/A7ZxogiICIOx/bZij+kEw6/ldv0qUFoHNxHcMWoVL19Wgbl2F6SyLKna59xQYmY8vdoYpSyphvQlIxzB7ZmaoFrgfFN3oqI5UBkk66eU3HTDxPaHiVur5V8Hvk8DUed/zbRD4cbWOUiofEiamprfW1RcV4X4tNvrRJOgRzwOGSnv47IGYfpMf47HNLKwga2+RomsYs+7xD2L4XUNopx7c0SDZ3av7+gLtZpsanG0Z67zaADl3kYETrigo6wF1r8AATrhcoFNsSN1pLe9mTNR1YRn0VyH7XLH/zNQ==
  template:
    data: null
    metadata:
      name: quay-build-secret
      namespace: manuela-cicd
    type: kubernetes.io/dockerconfigjson

