apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dest-docker-config
  namespace: product-catalog-cicd
spec:
  encryptedData:
    .dockerconfigjson: AgB6HRTYTOCymx0uPGoZqiZqkkju1AemNYZe0+WRhCI9b8bJ5WKH0hXkHYDEnaIORgW7ULIV9PAXDxFMmOj8hyd8IQSIAMjMd3qrDRkQszeTzAKCLxXW2ABBhbbqKcUfyF6lphVWcz/cVOYKZxHMGI1aPusgEcuU23wVyNvyilH9BKGPbiH4cX+Cjz8ZUeQojN+BCjzgEtLBL4WiVnHwOVkdftmp690AmHUFLxHi00WZztvf6us7m2uzq8BKO0kNZOOYPiKvME6jgg81nMJZU1kXLG6UptGUGXfKcjvKppQC97xDw1Gpp0hBlptQ3eJX6HrPjrjXrq3vpngZ5WjDAyMjY6J0Lzx8F9u9M/RT1WshWzMl/8tJaxIXCZDb1lSm2rEdN+KptX1zKpz/iDrz51e3RSr7/CPhU9wXi2BRe9dOm1A0Pr8zKJj5Hp0KhnkqKsfRk2avJIgMs9f8EvlD6kjpVa0gwfOFleaWrkHvjhyXanYUAiJbquZsWr696LyfsnZA4x1nLL4XUoVIUK+MG2/l/uVzQoksaiTNjHh7ACB/f/AdNO06LILBrGx5MZWiUkHBRg0lufehuP2Fggm4IM83lomEZOpE5GOp0lxV4o0jXaIfWVLutGdNG6N3/hM/bKFf4vQ45yvIqJmrlxRaztKH+qMOQ7z6GYMwNaY9CwyGNKmXsQQFmFdcqb2/ZL1j9PFBmWLMA5b+SGFZ+ftPUepSQQJRd3mgH7CuDev4SpCngAOjPH+4MMAg89KDfwLwSJReMaa22ZZa7pe/bCCcJK2pu02rZ6qZsOo5qaojLN3A+m+s8WUNSRmQAM2FACzAWQa+IRAdkz6LaVdThvpvdQx7Rs1drxT2GL/5uHwvIPKAejTUBHICgdruaBQ/Z0IgBQyxlziyeokpYiCcv8euIDNnE8FoJQmydym9QJ38c/QzgG5wBJYa5Gh8xgfFeOIPU7CMZ2elVGgV6EYel+g9mpz/UxiYvQRfqSyvkd4mGmXe9Y4uFQ==
  template:
    data: null
    metadata:
      name: dest-docker-config
      namespace: product-catalog-cicd
    type: kubernetes.io/dockerconfigjson

