apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dest-docker-config
  namespace: product-catalog-cicd
spec:
  encryptedData:
    .dockerconfigjson: AgANIqDYVDDB2BDyP+aIkcDUe6RPestZiVLn6/ctNAWB0o/OZyG5+/H0VWJkaG+vcBzw3PmT2qASqtaCK8Nnb80RBE2uNVoRkiYBxgwgajzYFPxmBJpESrIgR8xFs6t3A+x9rHeYBpfWdgzBnQ+JfknA6wYBAElYrb/rx9N7jHrY1hzjuHZ5sFR2zVgOc2fpoGJqpTgsiyuujrgSLeU/gMUT+qMorTEjw2FKb5mZrgoiJA09z0yBSrkn4PNWxRlTuMik/2kdgR3wLJaMbhsu6/IRp7ht7a+/mzfPgQbTHeaIPcynTEhB9r5yoKvhuNJ7ExoJdESZKsfIp8m1XpQeHQwKR7y14LopRbq6+otXhZtXAOKutfCw0/2XXElRH3NMYGJYmpfwV6hNQQNjgQhr4AzHWptjDYruAPiUuErKOrsRuSf+psRX1umF99z8uPQ5CljpZqrzVfSnIgnj9JuOxwvASk8u1DPlUo8ecqQ9SHFC9+qY6hrgopGtnlyZ7/L4BEizy8wvr3iHS6pLLx1lFfdxy0fH4bJbcOtJyQVCl5rUROzu54FfeLb36NZTnboGFWnxjNNdYRgfKLamsj+Yki16l92wlsISEnYjKQlUkxINwzMcvkffzYW7ucdnbCc2NlfYWR43gUZfYAa6i753VKt8LCDhC3LjMEczpqz6rnSn+GRbIAo7LuhGttnsb8XuXuHPH+BqAzjwVHXZHn+olZpXQeLNlYp8xSNVAzuu+djzWf3sfG5Kp/Z05u5yYDgG+hQ9/BnZnko20RVZXinkmWQTjRDDRpHJrbxmgiLru6m41i9u8lcU+aEaF/a7gerqoXcz2N81IeJ5oe6JwAf3w1xbD/4PQ1RRE1naXVscxdUf98oIacXk62FLNQz1ZqRD6lsY4B3hK3TtPcaqog50qoRBDnQDuyaADAKqezUwbNGGS+aTySV/5+Y7KSAeXUh7fz84W+ZXyF00c7OwZy7XSxGforGEtNBBVfIJxkmprw/vbMn54Q==
  template:
    data: null
    metadata:
      name: dest-docker-config
      namespace: product-catalog-cicd
    type: kubernetes.io/dockerconfigjson

