apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dest-docker-config
  namespace: product-catalog-cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCjklKWdw/hYLzhY1/vPgzxZdpijGpf5fCuCXAvpf+UynB6n8GN2KpRVZOHcs0T+oNMPntWReYoKinYnEt/VyW+wEygRhrPF07s522Ym6zhTieqasg4o62O+V3Jh4cDJMqzWNPyL/MNI58Hd2xN7o59I1pwpL1Lwhe66hqvPRWqVtP2Kkfy5RAb+8OeWLdK4QGYA3USqaLDKkfFFa/bds7Qwz91HjJLmw6vfJXQhzKdxNE1HZo95illqTWAvC22kwSD4SBY3eCfwuTEpIZczd8PWAdH7JhzPzeIRpzKg4Y2vOFh3wHpU/9DIw1higFyQeAM8L4BJqsn5uhZdSfIs9f+2DUgMK7LV+LBMvlYvcb9VzQVkZQau5z9SCgas5eDNwppyFlXVh3K3URUmb9Ab96bSJ6wDTIq0H07TwOfOCUZG09ZCg1RYpLiSy+kATDYWfOKhZ37CuC69pwccacwaBfbS2Yn/t7Zj2b7E0iur+kjEogCNok3lY4QqsdO9lzNEMZWh03rE2k+Svk9xn1UX30LpLAVZwV0F7+ySK2EwJtJaJFmFwLXR58DdRQKfFkSLw+HzVlioaMj/1H8FOxpnZ4sc/9Q+n9oWo/HkU+mcAVRW9IH9h8DnHnz/CCeZeHS0iM/UQ1JiWqd4HeT5bYp00UQH6UHv8G4K4udnBBc1XWkMqXkI8pIQE08nxFjntp8GVqfv891gcjfvsqGTXoBIPVs9gvYWe5fSV5UAUg+mADwUWqAnqwPxg67iJUdboFXDQhmhqHuxc/oMYY29CEZESf2Ipvd/8R/1rgETHgKstmA7H/QWFljPxq8voZIGSHrSL95L3ZbtHheip1CiPzc/2dP354UuULquOWTGdiZW4tFaYqKMbsLY89gegLoHj/kn7jTddfx2cJK3a2+y42gQ+Bt1WhTseLyG65/GviLITRht1YuDbp56Xp5BE8nKPDEJnCYAqOoRDlBtxuPFr/23NdYoXVxjZ1uAElane1oSrKKuFH2rA==
  template:
    data: null
    metadata:
      name: dest-docker-config
      namespace: product-catalog-cicd
    type: kubernetes.io/dockerconfigjson

