apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dest-docker-config
  namespace: product-catalog-cicd
spec:
  encryptedData:
    .dockerconfigjson: AgA1vcMFDFZuOHitQZGfdxCr+bES74ljdHX+yr9m96Wrh0NIBQVLkOATQrWaqIv5IVMZUvVJZQbhAcAa8pv0wt4bF+8dUK3A1W/WfZXRbDoHv/w4JzBEydAVOX2EWdLfhwdtL/L8ZkOESLIU+pQny8ciSOxHS7qE61h5NT4y5beY/qrgLl8YqjadGyyS/hY/fR8f8ki0ViEB2732SCc7WES1YtGmdW1enl2ZkZzTk4eSk8ITPuxsuduM19nkP9JABvQPX5fAWf5r+yCGvofA7EhauWDA37CP9VCof75QugulqmADJpBmt8fURbtdcuIR9F8XceVQIhODgTjJOKYDjD7MEItavn7uTQgvMIfrYNA8DAHX+pNsKDCvmhZWecwyR1FpSk75nTl7m/n3wJxQK/ZQ7FYVMctaX93gIa71FxEzMKUMI/uR+3l9K/jfWc8dPefMIi0oE/WEYBlmClBd9Arh2yY5RIxrwZ4B6R5cfOaOB/9hIoEyGtvgkVubF1YeSYdFZXT+xx5EnWT1B0Tlcd4GnFe1tjOnJ/UltmarmpV8OIl9LduQ1CK0j9dP6nZ72ER5I7ZKEIZ76ojjM8UTWeFEoH4cud7MIIdusudWNMhbpSb6n9YDmqsKspOT24fmKrue6SKrzz8jDdnphb9orIe/tSfkbRfmOzfEyaJqQPdU2QmU0PEz3LTF1q2Dn+vPtBlpHgweyB/L7zwoS/JdByhywFJMe1Bwo66WtPhwvWMHYaQI0bhOA3ebaCU3W0AsazqyXz63BsI7L4v413hrMkqKp6nmo5C04uTxIGxPU34WsX74f/QoHQ2WAmA+x3qnecDMTwMPPGBnzF+Vsicrt9JELT2WgVrHDFwEf1VCcA4DNZxqohcSvjBRCNWyVlVkoich279SfjvgMT7jVv8qv+cEAw0yq4iMj8w34vcNHzIeXWQWOb13pDbsWaYahdK5C3n/Rc/RR/pgy9YtOaYc096R3kHIs2jy8IfSDk/8OR/o8IaeWQ==
  template:
    data: null
    metadata:
      name: dest-docker-config
      namespace: product-catalog-cicd
    type: kubernetes.io/dockerconfigjson

