apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../environments/overlays/cicd

# generatorOptions:
#   disableNameSuffixHash: true

# secretGenerator:
#   - name: dest-docker-config
#     type: kubernetes.io/dockerconfigjson
#     files:
#       - secrets/.dockerconfigjson

- pipeline-rolebinding.yaml
- docker-sealed-secret.yaml
- github-sealed-secret.yaml
- slack-deployments-webhook-sealed-secret.yaml


patches:
- target:
    group: tekton.dev
    version: v1beta1
    kind: Pipeline
    name: push-prod-pr
  patch: |-
    - op: replace
      path: /spec/params/0/default
      value: sonarqube_host

  

# patchesJson6902:
#   - path: patch-pvc-block.yaml
#     target:
#       group: ""
#       kind: PersistentVolumeClaim
#       name: m2-cache
#       version: v1
  # - path: patch-pvc-block.yaml
  #   target:
  #     group: ""
  #     kind: PersistentVolumeClaim
  #     name: npm-cache
  #     version: v1