apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-deployments-webhook
  namespace: product-catalog-cicd
spec:
  encryptedData:
    url: AgAzPY0JZPuzA45GnzVhlL+3ZGObrZ2tUs65GVV7qpqiCxure+W5oHjhVSWv3/1vhGkzNHfsifE5wYIOI2U+89h1c1lM6GDK9opL7EopN/0tz8BPD4+q1wGJa4OOYBhnUJ6iWcuZGGPIT5rixJp02Rd4+C4mcx7DkEfjqxOVgjmSXNSXpxtxjGcY46GVvgrHNo3/AMW/qs5DVLsgrZFaMN0nQKibPVPywuSyU8czge9sEPXxy776NurXUaRe6f4nRa4l+izyUwYlAy0aATZ/WY61yMlqiGplrFzzOvhSptattwT1ZUGOvC4/1MckG0aGa9TbXUNyp6HIgm32OmibIiRET5dKSfg2fryURmsy/rngRfex9Xtmt4QzVk3avMIBnd9FcP+MzGiDAaOd1WxLjDHhl4KUJFRgR8u6oKcJUj1Y0lvQJheHnwsx/pHvvsWXTy9WbGPjJ5yPo9VIhIPsgKKujBTaimZ95c8uEJGWA9Guqu0Avldf4b8BEckZ2ZHLcvqhx8FeKDUVXag625FR0N25GbfZo0NM8g77nQTKS1DvbEVJyYxg+2kNOUpHwNLjfrPmO5AKeBPtbxU6SKocsHLC8f/4FxeNpnHTMO6yMSc1ZoKiUntWE3w25Nl2BD3BDkBLIQhLd7QwRHocLe8HVHQKQEwbUj35NWqJ/SJzyNFqk448RVlfGicRq++TNK6NzqnlvCWkr52TX/jKET6xMjeC4+d1ZF8Gh5Hm37FDMfRekh2zdkiwtv7Wqb3DKFqBOyKNxRCPNdo9iG6JR8RHAI4T/IhjovfAosFUogBI90Mf8vU=
  template:
    data: null
    metadata:
      name: slack-deployments-webhook
      namespace: product-catalog-cicd

