apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-deployments-webhook
  namespace: product-catalog-cicd
spec:
  encryptedData:
    url: AgBVLEziI1SuvXr4QLaO9nHJ8rgVcqhwmT//9jmYYCrEdHMLC+11xGPbgcT8UpX7Ucoq6CQ8+lu35ovmd+d7OsGfYrnI+B+DyUMQqV7nR9EreXk0yIA5uX/9Ek24yXHldFnCN5RHtKiQ6JXlBA87/Qchv/DiIsAKZebBIXV4prWXHIOe3y2iCAOX6pJ4onPyfyM1gr3DppbgzGQ8wQ0N8yW8CgZtZ/4XJy6FACa+hwqEt+OBAPyub/mW6J5jPZjHNCCt2YRKu31eolEGGppQ4pZ7gC2LyQF34x38unvaWqv/0GWa4+Kj4nn+JU6+FllVlAN5vVBfZKweXeuVlaE7fTLzk2OkWOdh4zEKzc5Hc4ZbpG7FJElD+lPPjkbH6BVXC+KsNW463Y3rng+bAECpnAz3p5UevgcoE4k34Wz2W/FgD+6M/3ItxuYlxIlradeohVpdgQahf+PKZKdoMPL5GnaQTRfkAO7cpjAwYjimanHxTqN54XcbNf5pBnfQ4v6x9FviU2nrnKzCh7bTfcFT0l2Q7J/K7/gdd4OrhZKEZHRuSuyal0zoniO+VGzjJQmr2digCc/e5ouexTpArMJFlkWt0Rpy/+IUqt9TiCKJtZRbxY1GNz65ujDtu+spb3DJNWpzmgqPywYozml5XrHd9J461RJ4uaKefrKVQb6+V5TyCmmrzPZZ8qaSRXYrwldQYgFc/tzsjfBsMyg1wgBm4jRqcd5UEM94s3rbBXDIs2hM5xZ4NbWh+lhdu8crUvP2ywxsyGfRZZt1iGLW+VO6MnUOqZIzUksBKh29Xc04V/pggqQ=
  template:
    data: null
    metadata:
      name: slack-deployments-webhook
      namespace: product-catalog-cicd

