apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-deployments-webhook
  namespace: product-catalog-cicd
spec:
  encryptedData:
    url: AgBZXAH8RUoRmpXX1uiCbYYvac4X+w4LXZPo6g+IzY0oLWGgBHnUyTC06e46YpSElKwj+5TMUwjdiuukXttWfDU5erskmuZXMWnELvrozS4dGJQnz4F7LOsWJM4NEn13v/kwLDdbtA6ngwgTgb1ExZDhcmlOMan1oA9Jf6NIB9l9SJBRo1JLwbFtFl/FM3UwJhhMiwSn+W8M0TEWWIwij+RsIqMoJIvspGk+IHGCKEVzy3GtPP5yvDf1reUpCuDaW7FFJYDwtfBUgFWWGM0fqyXd/BwDnLGF3FqgOpkr211hWFn6VGq4VH6dOjvP3gUTQpm3XMm5pXMxBbFnCNVyrY7/Y0aIR8ykRmx0PIJy48L2ILUPSJXfOxMJvTJdAEL3CEvs7pt9o9K6SdzQY5icIyQoMHRM9dTeW0nXb7+6aBFslbyfs8IiwOfj4h0Q83/7QoNtlJMKOAtX52cOyJHjWjv4vdM8xbFX/yrX96iWFb5nVHFZ9ux+75rlYOWDFFu9eYX4d7GKOt6TtRmLHCkGqewNVTDzNJHiwVe56BRnRJHOlPlAxBsUuauh8YtBw+CpXllOkJb8tErRCMz9bFZ49jj8hJPoWIx9OK1m6b8/cGEMKI5kmHnUuEon3aWVZJ0i77Ym9CDjY/TfGIjxMArL8/5KYnZn0BtFN/9MFeqoqwlMjF9NNT68qwPJRYnLwj5J6m2E0BN9fA9OSKpfjdhUb8SmiYbT+dSYe/E774XHDtOkvYX3P73d09LVnl0MzjPW2Q87uQNj7psJHRM3hW/sMglnDgOkoH+j3MU9/KRsIbVNo8U=
  template:
    data: null
    metadata:
      name: slack-deployments-webhook
      namespace: product-catalog-cicd

