apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-deployments-webhook
  namespace: product-catalog-cicd
spec:
  encryptedData:
    url: AgAkOOaJEJUELv4VitUbqlVf0GCeYCvo13OmgB4TYHsU7SSgAnhq82z25lN0TivAwoVm1ylbn5lh6ke2QpFZzd3Xz7X8Npgu3rmjnUqN/pCPmeoHh1/XCPc3AhgqDc0soPlcxlqYwgGrXdIjKXL5oIw3/V/OGpCp3bhFZArkeHxCuNImFY2UJlT2iBFRwQPwU53ZP85rrF3aFAqFHIgzOz0rHr+iq1aONOeYB81RfVId9YrmwIqEvWXB5x2fwfM/YYIgBV5PQrGiWp2x7QupyfHQ+lNGZRdiv6b4UdTcHmdIN5EvkldvxTLnpmvCCOvQdwhXkMgXltOvEmK5K2YFwghIwnGLGgUr91281Zs2odlP663Fx39Zi1+qPpQve14NLmgnR4VWAR1KoJlSKN1zWdQqa9tGUjnU3Kt9X+Wc78XrvIPHApz+dmqfeGrPrH8/l9047nxZrpr5oCMZisnvMD9BXNfwruvEKC49uweRGhGMS3Z69IVH1zHw0Qbx5K+AU5TgZFuopjDorQNqCzRrx1GtoaYRwEiHTh7skbiHRMvyP2SGNwvChqWckz5FSYI5yvvQi7FsF+dLykro/E/ZXxVkFU5o0xxLlQE3U31EthqALXnnx1ECiCgvYbAUuFBV0kaIACIJI5br0PP5trao7E1cejCOdDYPfQExwD/aIWiqr2h4Nu0/kSCkKt7P5dzf58357YSTfEcpht3ZVOjKcB+hEzAlz2eYQWzqFLjeeW/viuGQPWPavtapMFYKDPjiPTfxUWbVFBP3DJ/dOO4cSQ9Xtv1SmBGxGbU4Pmbc7ZiM2BA=
  template:
    data: null
    metadata:
      name: slack-deployments-webhook
      namespace: product-catalog-cicd

