apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default-view-rolebinding.yaml
  - iot-frontend-deployment.yaml
  - iot-frontend-is.yaml
  - iot-frontend-route.yaml
  - iot-frontend-svc.yaml
  - iot-frontend-configmap.yaml
