apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
  generateName: server-
spec:
  pipelineRef:
    name: server
  params:
    - name: MAVEN_MIRROR_URL
      value: http://nexus:8081/content/groups/public/
    - name: push-to-prod
      value: "true"
    - name: environment_gitops_path
      value: product-catalog/environments/overlays/prod
    - name: git_url
      value: https://github.com/luisarizmendi/product-catalog-server
    - name: image_dest_url
      value: quay.io/luisarizmendi/product-catalog-server
  workspaces:
  - name: git-source
    persistentVolumeClaim:
      claimName: server-source
  - name: maven-settings
    configmap:
      name: maven-settings
  - name: newman-env
    configMap:
      name: newman-env