apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dest-docker-config
  namespace: product-catalog-cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCUzUO5fxRgRf7/dO4Dbb1Usc7FXtEmcj9+md+sfuAQX4VU3r2vThr57PCIl6ChyvvQoy2NgcvIJvUCMfZYj8iS0rxQBr0rew771dE25kPvqPnqW4r/fSBUdo4ghd2jgJkhd+/DVYVch3i+Qy2JLmqw+pxYWphCJXkwUVGDqoZm+W+m765WYvsA2ytcPcMCWhgl2+6E3ckbXrHhPI0o9KV4SAibYHKL0NQMcYG2DXcIz/mun1qGlOqvWIKZCAYZ4rh3XwNHU+TIWI2VDUqygRLAyLZIRIfOHIkMaN//UgAsW9BsgVC2ayqG5Glgqd/avQ6n9VcNWwQd6WaAaeEifUODgKpJwtTt+pimu9bZToXwYS07tb4XdbEPeZHPS2zt1VbrCCWctH/WouTqdJQN4SEEYGNLwEit3xHjQ8rbubZ7aKHDIWHAfS93muBUqXTqxJk3H+UB1xNFV6OkBIWeaWmR+PMIVZ9hP4xzfCCpq5zvbKGESN0R/sWz43wYc1SacRI2EwBqNwgZcHxoy94OCOGxwUQr7YZ62gLCJJyOsuTNbC6TNuqHCSn1jnSUHdkNDAAE0bZSOjGry0XhrmCRqm8vW2zcMMRCaekINGnDDyY8zjf8B0W1smOvkBNoL0jg7fEQbKWXec67Iu53eMENQFFQI5rHHH4OSQ6KAB0CwrD68wD9Bv4g7agLOT4swNESvnSfq/Eedb4l6/4db6c7qlYXtfs1Ft4CUSoFpQqI/ZuM9gZi79k2/p2bjIm9nJL01+Ydvu/jKTchADmCrpVfyR+avqSoiGrlR6v6EG30KEg4WuwUHGbXlrMgIRwxzporzBAnwZSfTnMz7xUddbESyTHDxkJzDqDDuchHwsaKgGKIbjBt2sO1UwzoyVsSGG9uw8TpYpZBClWgJr9xs7Ceg6MPzZXmTJr0A5UdZVfWwE9y0kucqMmOCBbJMSjX57UV9FGbRtwuuRxWnVzfBoeh5XwOCr59ODynYGeKwOylL1dwpd+DRA==
  template:
    data: null
    metadata:
      name: dest-docker-config
      namespace: product-catalog-cicd
    type: kubernetes.io/dockerconfigjson

