apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dest-docker-config
  namespace: product-catalog-cicd
spec:
  encryptedData:
    .dockerconfigjson: AgALcyIbJs29cIKikl7jUk+w/OjmgZzKM2uXV/tkCatX9jG1L4GytMQYxVrf9GCVs7sl3dGd4/fJMZMy+aSsSvonaXbv3b65xImTWayJcZGd+k6hPqZdQ4ijCOgUujL3eheC3BDCeU2WSyCBTnNmkDzNAwb41clWo2FjD7elTlzK+RTKDUJ5llWcbi+rELA9ghAZLNVxEGe5cu2Z5Hp9ayr3XBRB56i9sF6vfAYM/7c0BGAt7C4yiZv+PgoaN0pzHPZazaD62qxbeohaHbIduVEDYpMfeiMSDoOHIfRV4zS7vurQDWJ+2fvsl8DELdVkBBcRNv9hKfcIypU8JQcODIzBjkZGUYf8xgx9UsH4JUsVLCvekd4B3CtiNWJcrs4hDr9ng5wLvvo/KE4lYnf2aCxgiMOmiPAntMf+whnzXpNfLOjnlhqJcDZug8GuW14lGG+88/da4vnZB8Sa0RGE7hLbGfa1Swihg+S0FM5FhYX1e3bu0bxqX5PpEY0T9iIWSYByMziBO0M+JP1e8CJVtMYMtjvm2x7jw9/F9dhRsgG8f5xRr/Zy3iE53n5we7+JoZmvwdlpH84zEX0+q1Fs1Zq5ZNesSCC82QrV7CU5eEX+2lR+kVGmR1fj2XdE5d94pdFoDlSdE+59nNMEGs65h3zgFQtDqBvD/zI4+1go7/vDYubnVIaxcANf67+hSZBpGAlU23fCOXsjz6MOi9Se35m7N6s4u4mYpR++upeq7RKQrYw4v5s6prs1PlzQEiAhPd6hLb87sRmwkAhHH+1dx6SWnp/4dqXZM7jTRm/+6zeT6B45jEfFZ8rloSc46t7whkQmKbGOUeNVIeA3+BMWRwTx+gWpp+r5Q4afEN5ElU7pimJZSQ0I6F5pDp4iGSepRsvBM96DdnWY8bGZCNNcgGkp8OMAb/cUfdis1cIJN8WJiKIEjdzHjrEWX0ksrIFCI9dQ0WemIib1riPRbqP9fZPBHA8uyGSJrRcHQYk2F7HA5PQyIA==
  template:
    data: null
    metadata:
      name: dest-docker-config
      namespace: product-catalog-cicd
    type: kubernetes.io/dockerconfigjson

