apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-deployments-webhook
  namespace: product-catalog-cicd
spec:
  encryptedData:
    url: AgBNMt2sQaHzcl33JseLqUQ8285hS5HcB6An+djldtrwpvhjVEitMhqYAjxPUGMXRWnlRgoygM421lm4o6J9OZS5LiQBNclixCR194WttfTm8QRCDgixW7IOBj+iWX+V7VPOd6i6sC/oclhFQkA+SocSlgNqzYzILwVmghw7z32O1Kgy6MhxU04PpNMNj70Q09js/5Y/ogLoPInvx0S2NkpDna7L4EouQjvhaCb/gCegZxUTzIH40CSvuSu64qeyoCQak9tI7fg2KuVsoYtzKIvxJxvov7FiDczkGRXmcBK46z1B0Ra9o6O1TOu7EsxpyzYWqJj6At+6RjmlGCFRsOfG1sv4aXndJVLfRU7dZWPDl9CeWW0v5uDCQpyRrUVCq/cKwK7XEhQd3awCwWKs0Kem0qvQDm+7bjGuydkw3ULwADJFleV+nm/7f/Jh6m3Jpc4+4xZ84AmGvlCX6AzlKDdupJBZhAm37qd/YkLh89dczGsuqZFAcEUZqN9gK3OpXLQZkdVSWrw402kMjg/nbvVUJQCiine5d0XwewmF2DcSiw7/knyY11HDuvvh3zPEpAA/R25jSVyvmtH+4rYRBvvTr/LW5zrlGTIhuB76/yhsspmqHLPchSdbpGXruOD7BD1if2+91lr0H+8j45/RuK6xkRsMGj5IRBiGC7RNUq9AwbNx9+7eDuCvRap7sB2kwMYWJVlgE7S1VMUtru6i5KSsDXCLUeK291/RRROezRmEQG6yGaEzREJXxQXUyjXQQjCDe7Gc6F87CJ3ddGn609FAsprEvp5BCTWtzoUy01nb840=
  template:
    data: null
    metadata:
      name: slack-deployments-webhook
      namespace: product-catalog-cicd

