apiVersion: v1
kind: ConfigMap
metadata:
  name: iot-frontend-configmap
  labels:
    app.kubernetes.io/part-of: manuela
data:
  config.json: |-
    {
        "websocketHost": "http://iot-consumer-iot-consumer.apps.cluster-nj7h4.nj7h4.sandbox929.opentlc.com",
        "websocketPath": "/api/service-web/socket",
        "SERVER_TIMEOUT": 20000
    }
