apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#- ../../../base/prod
- ../../../../../environments/overlays/ocp-4.9/prod


patchesStrategicMerge:
- iot-frontend-configmap.yaml
