apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: seldon-deploy-operator-rhmp
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  channel: stable
  installPlanApproval: Manual
  name: seldon-deploy-operator-rhmp
  source: redhat-marketplace
  sourceNamespace: openshift-marketplace
  startingCSV: seldon-deploy-operator.v1.2.1
