apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/cicd
- ../../../../environments/overlays/ocp-4.8/cicd


patches:
- target:
    group: tekton.dev
    version: v1beta1
    kind: Pipeline
    name: push-prod-pr
  patch: |-
    - op: replace
      path: /spec/params/0/default
      value: sonarqube-product-catalog-cicd.apps.ocp.46.4.65.190.nip.io