apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/prod
# No Seldon deployment in 4.9 yet
- iot-anomaly-detection-seldon.yaml

patchesStrategicMerge:
- amq-operator-subscription.yaml
- amq-streams-operator-subscription.yaml

