apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- iot-software-sensor-1-deployment.yaml
- iot-software-sensor-2-deployment.yaml
- iot-software-sensor-is.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/part-of: manuela

configMapGenerator:
- name: iot-software-sensor-1
  envs:
  - iot-software-sensor-1-configmap.properties

- name: iot-software-sensor-2
  envs:
  - iot-software-sensor-2-configmap.properties
