apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-env
  namespace: manuela-cicd
spec:
  encryptedData:
    ARGOCD_PASSWORD: AgADVmpFScMtGDr1qaIt6H5qd/FFJL5TyPwj2dys3/xDmaI47+YFTlE/UbCFPSaoV7KNUIBXLsW1Q79VjULeAMRjJpWmj/YSXZd0JGz7tpTQ/LvrbW6kS2n8plhEv+uhQ7/VWtvLXOVuiiIj7uoDFPWEdC+NNiBq/D8mzCuVQaTPOEWf/k3FfFULGRDFl3KnChRkz0ViBbTywjWIvCd/QL7HPDKO/5e2DsJLWM/uYhOklicpam/j74Z2rMW8gsLI/7ZleIDiLHsoqdgl76ZjeSdYe8qYxFVnE+pAF1KIUG2ZVibO9qF0ioZLoMGIrERJk+rv5mczqFT2xxfPEd7Rw2MS6bXH+/8qr3v109zgTzaOmVPWv0tv5RAUEpYAQPKzUCoOws7+bc7iSTuosF9hyQLn9sgkJLRCLBTJuk3nHKOWOCRnT32FbJAxL0+w5udVz0Qj/6oHIZ/2fDVy2cWMn9lff6AKP2TPQstn+7b5o3qYKc05ajdrryG7Rx/Or9YP48P5hCQF7s7rBSc7zfHmGX4+3xvbXu9aN4SCHWyqam83iU4F9mwXIK5uTA4qJSvQgG5NXdkV486Y26cC19T2HiTa9oXQuli1iM9UrRb4c1WDaqQSbgZewttVSlmO3XWK4aDe1oxktVhQo/oOpfqz5yZkxZ7nBcnd/vmboAa+sd928MEjy01V0sj/OfdHzYaW8N6Jhde/oTp6jtgYEactoVvucCiN9jJoty/bmpv3GVgVQA==
    ARGOCD_USERNAME: AgCQ61Jj/BR7w2byuEJFBmQdtSqE4zPUjoSBOIYzbvqSz+vGOrLOPSHnOYrgXBBuetIB0/LDEoweFART+UBSk/0R9y5IjF8iydW8FGYim/2mA5pO0bbccv2sxto1aS1g+nrH9seYNhV6NgxyxbkheLkh0QMDvRg6uuNFfZUnupLDDbW+p5tR6G6Y5KHCKVCQPXA9iJ345ICwlaH5LoxHVcKEiqywQ59QpqrZU2XnD30XuUgoxnAN2edJhJP2amQQv4Z9zSRzUL19pq8t5kunOF+da9KzYSwarZOxDUjG3ZttARI8T2w7HqGjzIJ501Jw2E0+VopX4MJukQynvVQbKH5yceryR9gQLFDQAv8BC7ea0wL9y6mclHqE/er4Wzh+5NWOD2Tw/Gc8eINbCtaRPXwWLGh2WtM6Iu9IjdgLXf4R4DCcs2r6mWHUduI+2X1QjWxPjzPbdIcLM4QQzUlOdNoXNVldQYRPiadoyWichl6VSxYeUGUnoSMaiXu8X0bpn5EqHiXhyhA5cA79qqmPEQ+uzFvij5cp8rVwS1ZAJYN3Kmvcyft/sZEMIaKBuvCBwGSFQYORtpNoBuyDE0Yv8gS/PDJjsOOGUEJrljIOTmsLvj0cNpCWiPhN3SE9wU3NDf7V95wNTIWb8BC9YjolSV1NzrxDl+mliYd+yT2cw2l2k6MbIgyQJU+2sol7VS/u2kBSFoQOvQ==
  template:
    data: null
    metadata:
      name: argocd-env
      namespace: manuela-cicd

