apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-env
  namespace: manuela-cicd
spec:
  encryptedData:
    ARGOCD_PASSWORD: AgCAT+TBMBhDODXU75U5Adu8rISVJcdEGmH9lcof6gOKVk4pna/3BXTQsLUfctZU3TO4bicvMahWNk5jheDSty4AoZ3KkcI1LRyabvX6KcCRaUxEBdYO89hxl2wwXxoQP6pWe+HNOxUdKshAnJ9Gst8OA46l3jkj+09UgQwJ3R7uZjwns201PyzJFzEzH+v71QkGh9H7ZCTAsh0pwdKaaVoYhm0ZVujSJAb/AeUnN28aL37/lejWIEi1a50hBWuisBwfxmFeNO1WRFYmzr4tFKSODOcZMRON14OzSqMH7KJjKwJ0ESRtjiQcwAf+ukVn2dNNdAClYPWIQh1kRDXGmJZ+cI/xZBHJ/XN1NUOqfSTaCaxAaFUEhK0Bb5/BWlp4+oZHlrkqr2RO8GopCJ86hyzh+zOpQG8lMuxNyY3MBnjWret4zReXoNWFh+2v3he/4MtUFvFCRTI9Rw+JnkZ1UoU1csncS7Ip//3maVNxySBUVIWMMU+2kUiA1FPPAHdTkKMyEzB+Yg/DdQy9wpofxhqmhX+s/upe1gkkqKdMEmchAD7+F3983e0gXmtpFfHwt7/AnsnOKwSAAmlsAk/IX00UdndlxvrhVkqvcX3O3iOCxeBmKgHGDlQTs8IDXprocyTCL/tDeAiDKn5ZMB0QWNVdcU3bJqtSPLk7Orv+JExCYyVvYA/hH7xT1UBLu1D1sktj9IgvIdLO9KJgdBtzUBraR46gJFSbAD8aFL/nqU5JQA==
    ARGOCD_USERNAME: AgAdja37J9CMNd80vaKxaUqH1ZLH7lA+UlPtEu+D8qv88UVaXTgdLq68TN7rsgxS/1fWZozvwB0X7bEG3367V5fGPd58SG/Xk/eDx13wvp3855PQdmtijm5LTw1MwGLwwjCRzlHDTzVg+Z5StkmXtk1lpj2J+frY0MEclTZjM5amY2jbCVqGK6yRoVEE3FdDUFgwlEXVil7bc4raPMtK8MO4h24mHrFOJzW5GpqVIOlx1w6QthVCDHOzvUmsHa0QTaUgHag64NyAYIcuydr6h9S4WXhMNZP0uQP06KYg+O4hmrR9HiR2sFYugpsEIIr67i6D5Ds262vNr5/IMsyXRCCwA9tCF3rlyhW/GOPMTz1dFFlrXu5soKL9BwK5ql6kqjGytKn6qnA4lGqDzpB64CUyhk3kjjCRSGqUysjgDITh70Rd9qRRULly1LBX5fIhmUBr14YePdxsed4lnTLWR6X0lqZb/nJND/8nlqPIm9zYwHMLMrIzHkt37PBlzXq96CnkwCsFvEHLqg367fmLvMw/ZcBaTZ1XKz6JwcsRqjCTWuUouqghrfgoocg4C1GYBg9r+tkIZMQ7jhp91RqwB+yrO70UHGDuGmm4en5fPiThKHQWFYxsdRopV5snbQ8r/0wf+HQKBDtVg9PMDWo34pdNseFyJJIonYKmR7kHnL4692zlGrGwGuaWYEIlEZZGR/V+WdxeWg==
  template:
    data: null
    metadata:
      name: argocd-env
      namespace: manuela-cicd

