apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github
  namespace: manuela-cicd
spec:
  encryptedData:
    token: AgBBhk+armfvOkiD2jAE5Jj2U1KTU8jt1G2iTi3eZKSVD1l9ruxXgcAL0vNqtMc3B3tD8++vE3bVxCssMJiTKdj7rzb1sJmqKS2DAkqQfz2ECXYW5qviJLF4nHQgJ4XHFd4jLXXe1Pst0acQzuHWF4j90prhRraNsXR+nydV83hrukuescYQPXOt6Uf/iF4xHE01MOOnq1ghYcqH2S9ZJ+QsRO9eJeOAUPiKErZbp5RIaPL6DGE5jh/j4kPtwogfseQE31cdOHcgivmvDgNm3CUJgekQmpXpRPM5Gt8+Ogknl6lMXtkdk+soeoLdBCDFYhD5eFSr4o7SZEkhPymdhMA8jmUN0cN3TtmlP3PZZdRD7CRBtZlODonPQrHHbMVed2IZPsr2mYOZ3gJShh0gT0hmuq1t9IMuL/kp/TKBwJgP2xchYweUwx7cztaXffpYHFm4SVcDvMv/n0RCN5t/3fwRdnMsRyanp5OG2P0Y7wxaTdWIlIi2rBcFxRPTeOcwMCE6bs2uz8g6yLCS57TgqvDObxAW85oi/9O8HEiodtyxaOJVbhLSWriS7/Iezo+RS2hXrY/MF28qJw6DXbeWwApOt6/kLbkND5OnKMHKYCZfvdhvyMhUrixuSqbzKKaJY6GkyUPpPdI4GWNstZfkr+ZI3owbFskMPAO7FBMWT98enyh9QloN1XrDBD56u21BOTn3ZfYbCWEY2qeGpaFvQJhTcmytwMaqFYn6sJS8vb6rDFYn92ut+YsG
    user: AgA6K5qtJsmRiul4O7jzqxcTGgk2D1P5+phhw9UJa06x64dUxrMnQIolnJGRjq6tyc2b6qiVLTbv4xCuNFAZ7R6Br3VU6HDzO5dI757IOJPq95EThHxyeG18xmJzMLkTjsPgx2nvrH/mj7Zkdw8LudSAZ+sjGJCbw96sihBJuG4fCvcG4/9O1MbXzJinn+FAmuOjnXUtvdzaQlerUXIN8ZjLvic64AxjTR+6rikACpQqJbzeVqpDtNA7OaAElvuWeme/NM3mWSetYAg1VphfTzGiHamGppvHVNflMIktZGud9cFJppj1sh0nQGKgbYmvb+mXVi2gPwxGdMsm0rjLK0RuVJUecCEy5iFvYLhV24X6F5z4g3bZkSuiqlQarwEUVbIjNpA/vLj2HyOqyOxeEgyrEuzoFC6rthjomaW0TawiM52lDtxyS0mrv8vsb7R4m0vB+Cf11lDx6flsTaLrSL3Y/HEYya5bux74ovPMeROzRIw3ivRjHSUkg05z8KjdT1xIXNvssJq5MjvFsu8anMizijGvar3tqqSXVU5+9m6vlM/dKMRgf6+ecxiD9WwWINJ6lshtmqj4UNunmosF6LeBdtGzQxCb2t9HOuDw/JCz5WrPtF0uWyGXt5pnOMrc0dOIw7sqnjr1tEOAS2Sx4LccNERKtdoXuzEsUVrG70mnZbtOS3igglWgPcEqCLGGdQg5eShIgepmiTv5sFOV
  template:
    data: null
    metadata:
      name: github
      namespace: manuela-cicd
    type: Opaque

