apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: quay-build-secret
  namespace: manuela-cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCS2aARcsj/N2aIITz9Kwch4jrt/23UYQQuzgJFONNyGiSTcxclPVeIUpxzG7GLQCMZxpFtsrgxhiFRrMAqQRn1iitBYnlyPUtBgRXc8BCBYo9/k1zX19F11jQeIUzZDV9RpDehlvZGDrLwZ2khLmLdM4Zap07I5w5QEHZhF6lSedattzE3YQugl8tUFOAfTjOXj9Ur8ILo5kWe6EgkUh5F2nE/sk/E7weLsHX6BVVc3OdHy46JYTG3YWQGDVFRCYM8eLXeGXCOpq0tOuWSJGkngA3c3TpHZ/8qPGRGRk7BT5/gsutUwMMve0vj25EHHci4Z8PussfGem95PzDK2l4Dwa6ANikR1yJMQkxSgF2VwoNZGYkY7vNe3eUSJi7mrg6jl9RDLRHs2HBjPnqoNtb69IGXK4NW6SYxgyoD84zoH/bIocXqyvRkZgNqJiGZ7cgSe1YaNxtr8N9DruydO9c9TLibaSWFdfOWOIzMxPk6hVQybOu47STO28Nb7maLvCT8ndGzh+KOoUQ/f5MatNkV3gGW38H/7ec4SwMs65rVvpSADnQuVpWGTXODFjcdq7IQfTBc0W3XCHRs9Cgl2YIdoAhuDlRLgTdQ6cNV1e3aYvGPRsuRxPN8dkGNa1E4VqSC7GhkQP/VXBpBo14Fdhh59wZ6zTJ4HEnB0YVw4wu5FkY1T9S2O6ikJjo+YXIF28TY+J5BwU58Oxee4BFBNtIpeSrb7p2BS+gPqfy1+9y1P/EErSHycmY+n2WcWoI/XLsaGAecJmAcjsHOQk8Ebd3CXpxtzl2XL+z0kPhhL6bEe3RK/jSxqXWpf70lrWbzqNgNXraBejkMNd300dKsZbGFJ6cj4t5+dQTycsYlZBucYqx/0J6oGnG6+6w0aKVyl+0gtXKL0qVw7WMPVLiRYrbDPAFmGL5aJgZ023RSfvcLrIUzTil+l1ibNb52tuvIcJ9Hnojzw1EbAjw7p6SItgACiECzCryfnsOrCvLkfJEVB3xtlA==
  template:
    data: null
    metadata:
      name: quay-build-secret
      namespace: manuela-cicd
    type: kubernetes.io/dockerconfigjson

