apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: seed-
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/sync-wave: "3"
spec:
  pipelineRef:
    name: seed
  workspaces:
  - name: config
    configMap:
      name: pipeline-config
  - name: github-secret
    secret:
      secretName: github
  - name: argocd-env-secret
    secret:
      secretName: argocd-env
  - name: quay-secret
    secret:
      secretName: quay-build-secret
  - name: build-artifacts
    persistentVolumeClaim:
      claimName: build-artifacts
  - name: gitrepos
    # volumeClaimTemplate:
    #   spec:
    #     accessModes: 
    #     - ReadWriteMany 
    #     resources:
    #       requests:
    #         storage: 1Gi
    persistentVolumeClaim:
      claimName: seed-gitrepos