apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: openshift-workspaces-
  generation: 1
  name: openshift-workspaces
  namespace: openshift-workspaces
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  targetNamespaces:
  - openshift-workspaces