---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: client
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  serviceAccountName: pipeline
  triggers:
    - name: client-webhook
      interceptors:
        - github:
            eventTypes: ["pull_request"]
      bindings:
        - ref: github-triggerbinding
      template:
        ref: client
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: client-webhook
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: client
spec:
  port:
    targetPort: 8000
  to:
    kind: "Service"
    name: el-client
    weight: 100