---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: server
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  params:
    - name: git_revision
      description: The git revision
      default: master
    - name: git_url
      description: The git repository url
    - name: content-type
      description: The Content-Type of the event
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        annotations:
          argocd.argoproj.io/compare-options: IgnoreExtraneous
          argocd.argoproj.io/sync-options: Prune=false
        labels:
          tekton.dev/pipeline: server
        generateName: server-webhook-
      spec:
        pipelineRef:
          name: server
        params:
          - name: git_url
            value: $(tt.params.git_url)
          - name: git_revision
            value: $(tt.params.git_revision)
          - name: MAVEN_MIRROR_URL
            value: http://nexus:8081/content/groups/public/
          - name: push-to-prod
            value: "false"
          - name: environment_gitops_path
            value: product-catalog/environments/overlays/prod
        workspaces:
          - name: git-source
            persistentVolumeClaim:
              claimName: server-source
          - name: maven-settings
            configmap:
              name: maven-settings
          - name: newman-env
            configMap:
              name: newman-env