---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-triggerbinding
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  params:
    - name: git_revision
      value: $(body.head_commit.id)
    - name: git_url
      value: https://github.com/$(body.repository.full_name)
    - name: content-type
      value: $(header.Content-Type)
