apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dest-docker-config
  namespace: product-catalog-cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAoQZT+lJx3SJxRiwFNj3bDxMe4SV/APxUSAnPJL7RwBer7sWpYq+rWyN0c+ZvUhJ4boIUhQ4QQ/1+pCaQPAlxKeiJvTIBqTH/s/2RKVEsaLJLQu+/D7RTiSCw9kv6CtDa2D2o/LfVEXsbm0AR0XbUYotNZgDI01pIeNOIw2dzlARtrrjqP5Kx+xTSRQ6SSNyEUP3YhgsqZ8I1wfODFMbd1CpkwKGEYDXDUGurAGQ1IjVnYI+t/owUNBFRygGXFkPef24Kv9TXcu9gl7mdYJvCCDFsg4DqDFHMI/iAm6nmyCDVpQM7qK6RLeq3qCXARnnduxOKuUm67CdyZzVgpSxVpJXYXqdEAAU0VlI2YtMACUxRl11mvsZ6NlLDPD3tgZ5kH6mLFBhMEpBg8DBKuk3pTGxciNoLWtO5pomqiRyKAtPG6ZsbPDNhNMQuB9PE+7sQ9nn9XeahTVdfCbl99JVQUaTC1hnf5izvRCVHRDlKiSmYutKs8DrC1mU3Wj3+zQla9bbjA3ZCk1mzloQvCG/U/skNEgWd8jvhDsWh1jYWBPgzCdT1fsiT5h98UD/y/yjkp3f6Ts2yBoyIdZYmv/2vbW3YoYIXC/+zMTN0+nIzbU05z0FkSWCi+Jj/l+IU3A8Za5cG8OKmxI/NXa8OmFHq3K3rvMIaOhq29h30DSqyKAK+2EIKh/cvHWW/v8XlqJC7Z79G8P4nHNqJ8Pzlc11VrvXFNxHo4qYUcSruHwPbeMxzfsBC0PFSHu2XKqJmwxQdYpiGvtXmuWMJfvWsmxCkAHSCWAcloTv1plJW99buUMu6vRFkOWuX55swno/2/lo5T/lUwbKxs8XPA72g6iWB203kRTJjKwHcDYtuLdPqVqlYAHLm8ARyJnsPbcLza5yRc+drHVp8M3SKio73QWHx3o/vEnBR40n1jiqHB1qQlrtaeP8eg9zt142S02pdPdxkMkos/CCEm6kGUJX7Tp8oR8szB/C16VU6wI75uiJgfyzcMzA==
  template:
    data: null
    metadata:
      name: dest-docker-config
      namespace: product-catalog-cicd
    type: kubernetes.io/dockerconfigjson

