apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-deployments-webhook
  namespace: product-catalog-cicd
spec:
  encryptedData:
    url: AgCq0bpkYQ8QVrkxmtoxhh24GPk8w32vMGGXXJSjNUdoKddbRseAh77K1Y5BEHBqOr9OpOpP8mbmSELMRHC6/zOoOoS2txtoB9Y5guPbcv+/2EFnVQ3aMn+oYmveLPcTlXSlfv3xpbvWdj1h/YzNazSF4JBpDDpDpZZSBzwaglGdH31yjeD+8LiffdluTaco9aZxn3wGb6N7i71w6+wuivTaD/nE15p9CXVJ3SlFXed8uMGcHszbAeVAHeAvcj6cenW71k7OIL3T239I8Sjr7EpZSw5bJr/bV0zyslnTVFgVxZ6Cjq7QUzjyd91xuwyuTuBqCqi52X/gLxOarxT4wSfss0iW6TJW/++B6YXW+G4acnrJAQKXVcFhEFyCeLybQbg6pvZ2vaRwQerZQH+wQMotQFmPZU1ffBrUB/96eONP3DCWz2z0DOWWTPRxkGtbTbEVitBRYfpgWbzrlG43pO3kj9IfZ4NzSskkK0l8I9swY/jQ5RBYc5WNfmyd4pb4uab8ZpD+znJNssHMx1tcc68eIuhZeC8rRyWuW4zMhUTKfutXs8Kh8QhqJorFmx++Rh+Rul65sf86ULP81h+WLoI2fepsMH/VQ3F5WwbyIImyzftywna51EMP7qN2XjDpLnxtDp7+Hr4frZkkltzUtUcLh2c5GobvbXEEWHr6tOyOUCTBUd5ln3DZ+MajEG3/hec/s6sYP8S71NyxYF1bccwt/MQ4pLww3MetBFo4+Ie3JMlAr9FugzvpsC8x1E4aTQI+QaTlLtTvmidn/de/sMTdrCw3FFU44n9ux6owVgToUZk=
  template:
    data: null
    metadata:
      name: slack-deployments-webhook
      namespace: product-catalog-cicd

