apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-env
  namespace: manuela-cicd
spec:
  encryptedData:
    ARGOCD_PASSWORD: AgAEoKuwU1TOK1xM+MevSJIxBU9THd1jBpJYdM04MS666lXskrh5DSzM5si28vcc/8dSnicGnvDtyk2Fw4ZPFZ+tQrhAcC957Whcl7ztsrP5tUhoWB3xAr5XSpsIcaZ50CjqQ4uFQ4sh55bVAWe/vVtV23P8lmN8DYQrlvyZhwlfUdVaYFpNw7KmAj8KWJ1UTtF0cj1ghASZ5PLc9yAowSzTaAWkmoIFwFdOKjk3TNjIcSnEr/WMr4O/G4/SmNxhBzwjdzJsmnTn62yeF3gubfqGUmEyARve6okQcjv6i0rBNWeTlv5LbsYPUGDhc8kBIClfYnooX6YPLit/vPqBhUeTbeQUN+nJJ2Oa7OH0SEn31wyPA7/IozVOexIBfcXrj6zmGXZP2YdxvpTdyRzRasmOKTE1afYR0MDyIZC4I/lcHcFoaPSxioUDavuXkjhWtn29AJaW8uMNcZA43tq9cLxMxjrw+j8STrhmdakuacf8zNNlRoiy6ZSGldx+ecfvAx+9UU3u84LQDVWlYG4Jb6V7kDVXep7G9hjquFBQvgtK1937rQ/hliHDPwNmBwAzAtjL5TzL61+XUGh98FH5fqwltWnmKP5MzkhG2+gEJiYKzKR9jOmksZqyRdGVlugq4PTpyu6u86+P21VaQr3sLv1aWbz9gpRvBEVJPGRxSE+DaliJizmNmYPYZEiOaZbcY5TiHm9s7doCtALT9Z9mFhw7cCbSMvRr5OndF8n0+w87Iw==
    ARGOCD_USERNAME: AgCN6jOZ4KvJAaptg+wxlHGm89kCRvQfpgRhlVILuXVCzW3jZs+fvb/4Dq2cO1fD8QsRbeyiJKeVLCEvD+cTK8YOt3b1+fyosxaTzGJ3R7v+XuacJbbCMdBFkDQTOE6Pod2QXPiwhBvhYTb5rsgYUTcxeestkKjzcEnpiSl6UwAZgW9OcrNQ9HfgINfJktzH2n7+5TVSyeZtLluZrwF8j9ovk9hsJQ4zafr1Y7AV3VODMHZwgwggxmxK7Q+Ov20/VU2QM5CVnEGUVa+CBXHHKmJAxzs7Nm3pq3FiAYQ1g3prs1Vz9+iVWVBjIifaIFFH9VUEUqWeyR88GamAqFJ6e9O1qkHcEquZZIjHKKBL6FNN3ZpNLIoOPq1XQZJ3IaZ0ZVlU0Mn27frbr/EM9yy8eaiyCcNLJEnOZZSSm/jA9DTIt+qCh2InfZKQIOWx2zotrHiWaWFjTm6EsQB6mXuhL41Ntqj4zYBGc+esFHFkwiYUhMdd9ukJPLh4VrmvcJzc0TkpTigvnSOQFRYsQf8vsIn/6dB/ljrqG3fPCERaaoiy1YASQRTI6NfcAJZmigG3QlM5JHtLR2zsUZf+8QoW3ThiMOnzN04YLT599tcsAmuCH0ksAr95yuCBVi7fwFNO4JxBClNlxa2IxP56Rs7tIB6tPbWTQ5n6AWZP99qnl2OOFfD+gS6Zr2Yud5D9N/2AZdSW/MfKfA==
  template:
    data: null
    metadata:
      name: argocd-env
      namespace: manuela-cicd

