apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github
  namespace: manuela-cicd
spec:
  encryptedData:
    token: AgAyTTulm9BNC1Kdm8oXjsBPNHLvefbu7cy94UdnWBLoCBphNL2y5rEKR7ohJEZJCfunfwrKT8MEPvzO2sEKjcokLBUr24dBbMWnoYgQubR6jrmPfnJrWlSdo+Sm92aNJ6KEUubCaPpPw6rcT/b575RpAw6yzHsE8uq7kO9ZnaUEY7w+6g8CqrEI+87AXDACprh0b9buSs9ucGpaeZ1na+Yz4V0Y/gM7ipWEX2rR/mwRJNIhjda6VPsVmkrYK6iHDS8ljCWhC8IhkjP3wriDltNEjnioyh9ylZcr+OtFfT5qlXTZK1M7BYTOIFzyNZAHEmsIi8gljteHlZiXMRpHODhp/Duilpq9ymL1ywj5QoS+r4amKn2rvkw7UPRkjrq4r/SL0XF97SXE84EpWCq5/2GJgUWftPZDWHoEE0i5ZVmr6tj+A9cCt8/+a4N0mH59yCIu/mYAMzTB2Ts0Hugd8BaOXBZUCSMsuTc19Llz3No/BtHCp17uT3ieS21FFu3Cx2r0g13ZGxclnSk+2n6i6eFqWSo85Got5AeXLJSuQjrmr3/rqlEr09Y5X+e1R1o+3J1VG0/NoPcspGB0sYmEyP143MnjPlOKAYHjDS7JiFTHCyXlkZvw4+hTZ4BnWuUQvDR/XppbzpfBFRPS0mUh5dE3ZTzlKxH/pECRQzTyW1h18lc7B0Al+Tod73bHvJxINvNbvCQfV8UVasFiCJvoVZDJJTEoyoLjT7sQrZYqetIrcLQkOtf/BZ9b
    user: AgBFmovNEJRk+iF458Kwa/C+F7m4r2mCPavYZEqLB1cHGFByERh1LXNkJcFjffZKhygVCJDaB7VoM3pzwoHkkpnGpglBudu3aCWFUQL0vvBXhLNlgFuEGVzSFeOE4y0YERh5R57O/bdzGQGxDVEXnUKpc7RyHWK3+WPeH1EY+NEeEKjvyvKl0JPn4TMCHSQx9PHSy9ssbCed2XEEMFp/9W9Yq2UIAVT6BZomCyzKSz2Hz5TfC4Ry49UfrZiOnXj8BjjdyMrbz4hC3fKsBuLSnyZ9Gc9CVLz7WBewglvnp3T/6rfNITn7IG37nzOEYjVb7KJEUYhN1pDxGb3AxN6DaFusQomZX1ABz3gYaDbiGCOD/plm31KDnwk295eJn2MLPFuk8UnLmv6UYM+cV1gyK5Vrv7M8tmsUTK0ixGml+1bNJ4OZYZtzPi+YmO64jlPFkbGJHKENknSRsF85VgtItmA/s8iyIIgqWWNRILIwvsNV3DgpNSDucblAqRNeCjFf8iU/6e5748NciOLQCyNfG68ucGfZAkSd8ES8+yzrLpY9+Nvg+zRugwDKGG4GLDPf1fCiD49ScNARdhtDtVeeT36QbwQo+yGYswHCmsbeTzq000QMgNXfYGzY81jlDj6EfsXFx7Gb/ZVRqcBdnTNmP8COZR5SSZKno9hTbq+AtjOqukR+u5UOXhEo54WngjJh7cLKK18/bKBxO6p0Xxeg
  template:
    data: null
    metadata:
      name: github
      namespace: manuela-cicd
    type: Opaque

