apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: quay-build-secret
  namespace: manuela-cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCVswcsOWcdfUW+x0NSJChXoi4hFy8YYVHvq/XzQSA4YxmdCXdJvH9f05HyyNvajwvVT9MUzqVPPt+iO5bocg+TmkxsnhgjzrYqQgLL3+3LpiYrnU/p22MxHDnUavGW5iuPF92Ys7gjbGzvTdYoejvxudx9vefwT4MOAYO6HC8mL2CCfXYItd0R9wdq9WMFHprQBftvrGrMDthMf+DrgMNDVW+cO8MiSuJfbr4q99DQ5zTi1ymGGmGDBZ/QO8kM7FooXzLk7xdmFAOEc/5gZNrmM5eBlGJJjsHk1AX58c4yUbrqRhqwKCHjo4X0L4gke0z8klrEdoLE4Q0IpWVD3guzlx8jDiy3wae7Ng/aWOETuNMktapTWzgnA81Bts7n0/bOuX4APM4cny4IATwmQRkRZK5EWd/+rzVdbWNKRSn2BPpa3/zwaMI2vMSz0zyIkqr4lkJFQh7+PhoyyuczAQ+6ur58g7WURiru/OgwQRHnXKWM8t7AotQaYNNWcENKwwvQqUfsIzhknOOSH7KfBEZbmxF/xLIrHP5ltwjihqYwuWUwVVatWdLVWeusxlqDQtxF3lr20jsP++t3AedRSlDDm4hQaWmOKpcrMZ3PxhhlKp0OEt+w9OXJQaXA4MWCLmE2NwfQgsB0j5tvfP5WpVsrijQaRHPgX0tyxsA+bei3+MXmcEhFmZExCFs/fVVb5cUnp98ZQvEnW+IlFj27+IgHwFOILHSXfh44ZBMLgt1iwDtNhe7Bv9zqOaIWK/VSmhZ3GElwXP6SViCavs/VjBxpJORTHPJKOW+bXBHu9SW2RYXU/mS/9V5ZrsXy2vds+fVhrbmV1drwFmg6omDV/loGCtVMYmMbwMtTmRWLdsQcqBzWOtHxbRov+FRDJEGF5zc3HS/69PYDLrxRY4R8cXBmvJe+BhsmH0ytEYvk+7feZe/mudMeQ4nQcI/Os4VDNpufB4hVg4/uULKPi3UG7OnKMXvPlcdmIXTqVq62KUhOB1xyAg==
  template:
    data: null
    metadata:
      name: quay-build-secret
      namespace: manuela-cicd
    type: kubernetes.io/dockerconfigjson

